### ISSUE TITLE
Configure Build of apk branch to only build a) dev branch apps or b) master branch apps on merged PR

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#10]
Please configure the building of the apks in the apk branch as follows:
* Only build and overwrite apks from dev branch once dev branch PRs are merged
* Only build and overwrite apks from master branch once master branch PRs are merged

The goal is that we see in the apk branch the different dates of the last merge and save build time as there are less apps to be build.

**Comment by CloudyPadmal** [comment]
@mariobehling we've to add `GITHUB_API_KEY` into Travis Environment Variables

**Comment by mariobehling** [comment]
Nice! However, my question here is different. Are we only building the dev or master branch apks on merged PR in the specific branch? I want to avoid that we are always building and overwriting all apks of both branches. Only build the apks of the branch that merges a PR, please.

**Comment by CloudyPadmal** [comment]
With the current configuration;
- If a PR is made to dev branch and only when it gets merged, then an APK will be generated from the dev branch and it will be added to apk branch with the name `app-dev-debug.apk`
- If a PR is made to master branch and only when it gets merged, APK will be generated with the name `app-master-debug.apk`

**Comment by mariobehling** [comment]
ok, awesome!
