### ISSUE TITLE
Poor quality rocket image in rocket animation

### ISSUE THREAD

**Issue by RohitJain1103** [fossasia/neurolab-android#101]
**Actual Behaviour**

The image quality of the rocket in rocket animation is low. 

**Expected Behaviour**

A high definition rocket image should be used for the rocket animation. Also it should be of vector graphics.

**Would you like to work on the issue?**

Anybody interested in working on this issue. Please comment.

**Comment by suresh-gandhi** [comment]
I would like to work on this issue @RohitJain1103.
