### ISSUE TITLE
Make an Awesome Splash Screen

### ISSUE THREAD

**Issue by vishal-sehgal** [fossasia/neurolab-android#114]
**Actual Behaviour**
Currently, there is no Splash Screen for the app.

**Expected Behaviour**
The Splash screen will make the app more attractive and meaningful from the launch of the app.

**Steps to reproduce it**
This feature should be implemented when the user launch the app. The launch time will be 3000 milliseconds.

**Sample Screenshot**
![Splash Screen](https://user-images.githubusercontent.com/20669217/55202875-4b11c480-51ef-11e9-824e-ac913b41e982.png)

**Would you like to work on the issue?**
Yes, I would like to work on this issue 👍

**Comment by CloudyPadmal** [comment]
Now there is a splash screen
