### ISSUE TITLE
Improved Home Screen

### ISSUE THREAD

**Issue by vishal-sehgal** [fossasia/neurolab-android#116]
**Actual Behaviour**
Here is the current Home Screen Screenshot:
![Screenshot_20190329-182455](https://user-images.githubusercontent.com/20669217/55235461-9f4e9000-5253-11e9-820a-c43cf2710dcf.png)

**Expected Behaviour**
New and Minimal Home Screen with Cards:
![Home Screen Device connected](https://user-images.githubusercontent.com/20669217/55235575-e177d180-5253-11e9-94a8-213f111225c8.png)

**Would you like to work on the issue?**
Yes, I would like to work on this issue 👍 

@CloudyPadmal @iamareebjamal @mariobehling

**Comment by vishal-sehgal** [comment]
@CloudyPadmal @iamareebjamal @mariobehling 
I would like to work on this issue once the #115 will get merged.

**Comment by jddeep** [comment]
What mechanism are you using to get the device connected? And please learn to work with different branches. That will speed up your development. 👍

**Comment by vishal-sehgal** [comment]
I will use a Broadcast Receiver and the **USBManager** class to detect the hardware connected to the device with it's **vendor-id** or **product-id**. Once the device will be ready I'm ready to handle this issue If you like this issue or want to continue me with this issue :) @CloudyPadmal @iamareebjamal @mariobehling

**Comment by jddeep** [comment]
@CoderVishalSehgal the UI seems great. Go ahead buddy.

**Comment by vishal-sehgal** [comment]
@jddeep Done 👍 Can you please see it here #130
