### ISSUE TITLE
UI For Displaying Raw Data 

### ISSUE THREAD

**Issue by arishuynhvan** [fossasia/neurolab-android#136]
**Actual Behaviour**

N.A.

**Neurolab-desktop Behavior**

![k24bitSimulation](https://user-images.githubusercontent.com/7850717/55311637-08254a80-5496-11e9-9999-b770423de235.gif)
![rawdata](https://user-images.githubusercontent.com/7850717/55311643-0ce9fe80-5496-11e9-904f-7a74c99c4af1.gif)

**Expected Behaviour**

![neurolab-android-rawgraphs](https://user-images.githubusercontent.com/7850717/55311726-43277e00-5496-11e9-8f7a-e931ed849076.gif)

**Proposed UIs for Other Graphs**

![neurolab-android-graphs](https://user-images.githubusercontent.com/7850717/55312136-4bcc8400-5497-11e9-8885-79945dd967f1.gif)

**Would you like to work on the issue?**

I'd like to work on both the view and activity implementation if approved. 
The data displayed will be the same as what is shown by neurolab-desktop in the simulation mode.

**Comment by jddeep** [comment]
Please go ahead with this. :+1: From my side

**Comment by arishuynhvan** [comment]
Thank you @jddeep .

To all mentors, contributors and maintainers, please feel free to provide your feedback and suggestion. Here's the link to view the [design prototype](https://xd.adobe.com/view/17eb0a1e-4654-49a3-56d9-28c440035df4-61da/) that I created using Adobe XD.

**Comment by CloudyPadmal** [comment]
Hello @arishuynhvan , you may continue and send a PR to review. Thanks

**Comment by CloudyPadmal** [comment]
@arishuynhvan any update on this?

**Comment by arishuynhvan** [comment]
> @arishuynhvan any update on this?

@CloudyPadmal My apologies for the late reply and sincerely thank you for closing this issue. Despite my enthusiasm, I struggled to implement this due to my inexperience with Android development. In fact, I haven't developed anything beyond a basic To-do app prior to making this design.

I have to admit that it was very embarrassing for being unable to deliver this design after more than a month of self-learning Android (April-May), so I didn't have the courage to reply before this issue was thankfully resolved by @jddeep (you have my sincere appreciation). 

From mid-May until now, I have been occupied with an internship, a requirement for my graduation, so I have to stop my Android learning and experimentation.

By sharing my struggles, I hope to keep the opportunity to be part of FOSSASIA community open in the next stage of my life. I've learned to start my contribution only to technical stacks which I'm more experienced with or when I have the time to pick up new skills.

Thanks for reading this note.  Please allow me to continue staying in the gitter chatroom, even though I am unable to offer any substantial contribution to the conversation or code review.
