### ISSUE TITLE
Better Focus(Rocket) Screen

### ISSUE THREAD

**Issue by vishal-sehgal** [fossasia/neurolab-android#139]
**Actual Behaviour**
<img src="https://user-images.githubusercontent.com/43133646/51436139-25c38000-1cad-11e9-98ac-e7be98505316.gif" />

**Expected Behaviour**
![focus-neurolab-fossasia](https://user-images.githubusercontent.com/20669217/55341978-4dad3c00-54c5-11e9-904d-456da8c4be8d.gif)

**Drive Link**
HD Demo Video to observe clearly
https://drive.google.com/open?id=1aFVUzosrlS_WhiubJoCTbWXGkt-6HQ2W

**Would you like to work on the issue?**
Yes, I would love to work on this issue :)

**Comment by vishal-sehgal** [comment]
@iamareebjamal @CloudyPadmal @mariobehling @jddeep @suresh-gandhi 
I request you to please take a look here and let me know about this. I just finished the code and everything is all set Just need to send **PR**. No 3rd party/ any library used to build this. 
Waiting for response from your side. Hope you'll like this. 🤞🏻

**Comment by vishal-sehgal** [comment]
@iamareebjamal @CloudyPadmal @mariobehling It will take only 2 mins.

**Comment by adityastic** [comment]
@CloudyPadmal @mariobehling

**Comment by vishal-sehgal** [comment]
@adityastic I just send a PR for this issue, Please check it out and try the sample apk [here](https://github.com/fossasia/neurolab-android/pull/246)

**Comment by CloudyPadmal** [comment]
Fixed in #246
