### ISSUE TITLE
Remove unnecessary created class

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/neurolab-android#143]
**Actual Behaviour**

Multiple classes found for aboutus activity.

**Expected Behaviour**

Only one c;ass should function as about us activity.

**Would you like to work on the issue?**
Yes
Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by adityastic** [comment]
@CloudyPadmal please close this

**Comment by CloudyPadmal** [comment]
Not necessary
