### ISSUE TITLE
Rename "app" to "neurolab" in string of apps on apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#15]
Please rename "app" to "neurolab" in string of apps on apk branch.

![screenshot from 2018-12-08 11-29-55](https://user-images.githubusercontent.com/1583873/49685029-b0289980-fadc-11e8-90ad-3181bc9abcb1.png)

**Comment by GOVINDDIXIT** [comment]
@mariobehling  can I solve this isssue also there is a need to update this in update-apk script for future apks

**Comment by CloudyPadmal** [comment]
Yes, that is where the edit needs to be made. Please send a PR with the change. Thanks.
