### ISSUE TITLE
Using Pojo Preferences.

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#150]
We can use https://github.com/hitanshu-dhawan/PojoPreferences to save our POJO variables into Shared Prefs from the Launcher Activity. This can be used to save the prefs of the user for launching a program mode. This is not some huge data, so storing this particular pref data in a database can be avoided.

**Would you like to work on the issue?**
Yes, I would.

**Comment by jddeep** [comment]
@CloudyPadmal @iamareebjamal What do you think.? Please do give feedback so that I can proceed.

**Comment by iamareebjamal** [comment]
7 stars, 12 commits. How does it serialize nested objects? Not sure about this

**Comment by jddeep** [comment]
> 7 stars, 12 commits. How does it serialize nested objects? Not sure about

@iamareebjamal This is a new library created recently and yes it will take some time to be stable. I suggested this because it would have suited our purpose well. I shall be discussing more about the library with the author and then we can come to a conclusion.

**Comment by jddeep** [comment]
@iamareebjamal Currently, it doesn't store nested objects. But we can store all primitive data type objects, I think at this stage this library will serve good to our project. Moreover the author of the library has `enhanced` this issue as priority and soon it will support serializing nested objects as well.

**Comment by iamareebjamal** [comment]
Then it's useless for us for now, and it is already being implemented using JSON

**Comment by jddeep** [comment]
@iamareebjamal Okay then. I will be closing this for now but once it serves to store nested objects Can this be implemented or shall we continue using JSON?

**Comment by iamareebjamal** [comment]
We'll see
