### ISSUE TITLE
Import sample dataset into Android app

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#152]
**Actual Behaviour**

Android app needs a hardware device to test functionalities. To function without a hardware, we can use a test dataset recorded from a real device.

**Expected Behaviour**

Implement an option to import test data set from [desktop repo](https://github.com/fossasia/neurolab-desktop/blob/master/k24bit.csv).

**Steps to reproduce it**

> Not available

**LogCat for the issue**

> Not available

**Screenshots of the issue**

> Not available

**Would you like to work on the issue?**

Open to new contributors

**Comment by vishal-sehgal** [comment]
@CloudyPadmal I would like to work on this issue

**Comment by suresh-gandhi** [comment]
@CoderVishalSehgal have you started working on this issue.

**Comment by jddeep** [comment]
@CoderVishalSehgal Please confirm if you are working on this.

**Comment by vishal-sehgal** [comment]
@suresh-gandhi @jddeep Not yet, but now I'm working on it will let you know guys If faced some issues 👍

**Comment by jddeep** [comment]
> @suresh-gandhi @jddeep Not yet, but now I'm working on it will let you know guys If faced some issues 👍

Awesome @CoderVishalSehgal sure 👍

**Comment by CloudyPadmal** [comment]
@CoderVishalSehgal , any update on this?
