### ISSUE TITLE
Port Neurolab Desktop Java App to Android

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#17]
The Neurolab desktop Java App is available here: https://github.com/fossasia/neurolab-desktop

Please help to port it to Android.

**Comment by subham9777** [comment]
Do you want the entire app to be built from scratch or is there a sample already built????

**Comment by mariobehling** [comment]
The code from Java needs to be ported and the app built from ground on Android. Would be happy to see some code.
