### ISSUE TITLE
Adding the Intro Guide Screen

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#170]
**Actual Behaviour**
* The application currently doesn't have an intro guide screen at the very start of the application (for the first time) as a tutorial on how to use application’s features and functionalities. 

**Expected Behaviour**
* The Intro Guide screen should be added at the start to make the app more intuitive and appealing to the user.

**Screenshots of the issue**
![Intro Guide](https://user-images.githubusercontent.com/22399995/56860654-a2ee4780-69b6-11e9-942f-8b18f136da57.JPG)

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@mariobehling @iamareebjamal @CloudyPadmal is the UI looking good and does it match the theme of our application? Shall I start working on this issue? Just let me know if anything needs to be changed or altered. Thanks

**Comment by adityastic** [comment]
@suresh-gandhi the design looks good but I'm not sure about the colour scheme though

**Comment by jddeep** [comment]
> @suresh-gandhi the design looks good but I'm not sure about the colour scheme though

@adityastic We are going to look into this at a later stage. Currently we are implementing functionalities.

**Comment by adityastic** [comment]
@jddeep yeah it should be prioritized

**Comment by suresh-gandhi** [comment]
@adityastic I would keep your suggestion in mind when implementing it in the future ;) Thanks.
