### ISSUE TITLE
Add the Networking functionalities (Forwarders as well as Receivers) 

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#173]
**Actual Behaviour**
* The networking subpackage is incomplete and lacks several essential classes like OSCForwarder, OSCReceiver, SerialForwarder, SerialPortInterface, and SerialPortReader.

**Expected Behaviour**
* The networking package should be completely ported both the forwarders and receivers which would include finding and adding the correct external dependencies for the android version of the application and porting all these classes correctly for android.
* This would help to carry out our tests either on the hardware or on the test dataset recorded from a real device as @CloudyPadmal mentioned [here](https://github.com/fossasia/neurolab-android/issues/152). 

**Classes to Port and Checklist of the work** 
- [x] Finding and adding the correct external dependencies for the Android version.
- [x] Adding forwarders - OSCForwarder, SerialForwarder
- [x] Adding receivers - OSCReceiver 
- [x] Adding other utility classes - SerialPortInterface, SerialPortReader

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal @iamareebjamal @mariobehling. Shall I start working on this issue?

**Comment by suresh-gandhi** [comment]
@iamareebjamal I am working on more of the checklist points of this issue. I added them together in a single issue as I found them related to networking package. Shall I make new issues for the separate points then? You suggest.

**Comment by ShridharGoel** [comment]
Needs to be reopened

**Comment by ShridharGoel** [comment]
@suresh-gandhi I would recommend creating sub-issues from the next time

**Comment by suresh-gandhi** [comment]
@iamareebjamal Needs to be reopened again. One checklist point remaining. Actually, I found all the work related to the networking subpackage and so clubbed them together in a single issue. @ShridharGoel I would take care of adding things in separate issues from the next time. Thanks.
