### ISSUE TITLE
Neuro-Visual Feedback Module should be implemented

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#174]
**Actual Behaviour**
* Currently the application lacks the implementation of the Neuro-Visual Feedback Module which includes the classes - FocusOMeter, FocusOMeterGLRenderer, LongtermFFTVisualizer, NeuroGameRenderer, NeuroGameVisuals, OSCFeedback, ZenSpaceGLRenderer, ZenSpaceVisuals.

**Expected Behaviour**
* All these classes should be correctly ported after converting them to Android Version.
* The usages of Jogamp should be appropriately substituted everywhere with the correct replacement for Android Optimization.

**Classes to Port and Checklist of the work** 
- [x] FocusOMeter
- [x] FocusOMeterGLRenderer
- [x] LongtermFFTVisualizer
- [x] NeuroGameRenderer
- [x] NeuroGameVisuals
- [x] OSCFeedback
- [x] ZenSpaceGLRenderer
- [x] ZenSpaceVisuals

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@iamareebjamal @CloudyPadmal @mariobehling. Shall I start working on this issue?

**Comment by suresh-gandhi** [comment]
@iamareebjamal could you please open the issue.

**Comment by jddeep** [comment]
Will be adding FocusOMeter by today.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal needs to be reopened. Some checklist points are still remaining.
