### ISSUE TITLE
Missing Graphing/Chart Library for implementing intuitive and engaging ui's

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#185]
**Actual Behaviour**
* Currently in the all the four program modes we just have a rocket animation which in itself doesn't make much sense as it doesn't depict or specifically quantify something. Instead, all four program mode activities should have appealing and intuitive user interfaces (bar-graphs, line-charts, heat-maps) for enhancing the user experience when dealing with those modes. 

**Expected Behaviour**
* Intuitive UI’s like bar-graphs, line-charts, heat-maps, etc for portraying the degree of stress, anxiety, focus time curves, etc in the all the four program mode activities to improve the neuro-visual feedback.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by adityastic** [comment]
Use Android MP charts

**Comment by suresh-gandhi** [comment]
@adityastic Thanks. Even I was thinking of the same.

**Comment by adityastic** [comment]
@suresh-gandhi Don't just add a library, Add some implementation as well
