### ISSUE TITLE
Bad and messed up UI for the Launcher screen.

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#198]
**Actual Behaviour.**  
Bad and messed up UI for the Launcher screen.
![Webp net-resizeimage](https://user-images.githubusercontent.com/43133646/57666952-6a3da780-761f-11e9-9540-953d3af39d12.png)

**Expected Behaviour**  
The UI needs to revamped,

**Steps to reproduce it**  
Run the app from the development branch.
Open the app.

**Would you like to work on the issue?**
Yes, I will work on it,

**Comment by jddeep** [comment]
@CloudyPadmal @mariobehling Have a look here.

**Comment by mariobehling** [comment]
Thanks. Please keep the UI simple. Follow PSLab examples. Keep top bar straight. No curves, please. No need for "Welcome".

**Comment by mariobehling** [comment]
Please avoid pinging everyone in issues.

**Comment by jddeep** [comment]
> Thanks. Please keep the UI simple. Follow PSLab examples. Keep top bar straight. No curves, please. No need for "Welcome".

This change was merged recently having these UI changes. I guess i need to bring back some originality.
