### ISSUE TITLE
Implement the Serial Program Mode 

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#203]
**Actual Behaviour.**  
Currently, the application has an unimplemented Serial Program Mode. Also, it is devoid of a good graphing/charting library. 

**Expected Behaviour**  
I wish to implement the Serial Program Mode and also add the corresponding library for the same.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@jddeep I would suggest adding a similar issue for the VJ Program mode, to avoid PR clashes for the other developers, and start working on it.

**Comment by jddeep** [comment]
> @jddeep I would suggest adding a similar issue for the VJ Program mode, to avoid PR clashes for the other developers, and start working on it.

@suresh-gandhi Yes, I have decided to open an issue and work on it from tomorrow.
