### ISSUE TITLE
Improve UI, separate activity screens from settings and fix spelling/capitalization 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#207]
This can only be a step to the final UI. Merging this as WIP.

1. Rename area to settings 
2. Separate the different settings more clearly and add an explanation what they stand for. You can refer to any popular app like Twitter, FB, Instagram. See how settings areas usually look like.
3. Explain what the area Focus/Relax/VJ/SERIAL stands for. What is the functionality?
4. Please adhere to standard capitalization in apps and change as following (Please take care of such small things yourself in future!) e.g.:
* Audio Feedback
* 24 Bit
* Advanced Mode
5. Simulation: This should be a separate screen with a button "Load Sample" instead "Load Resources from Phone"
6. Avoid all capitals: Focus/Relax/VJ/SERIAL

**Comment by jddeep** [comment]
I will be working on this,
