### ISSUE TITLE
Travis build does not generate APK in apk branch

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#230]
The travis build is supposed to generate an APK in the apk branch: https://github.com/fossasia/neurolab-android/tree/apk

Currently this is not working. Please help to fix that.

**Comment by CloudyPadmal** [comment]
There is an APK file generated 3 hours ago :thinking:

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Also one has been generated 20 min ago just after the most recent PR got merged 😕

**Comment by mariobehling** [comment]
Ok, seems I missed it. Thanks!
