### ISSUE TITLE
Implement serial interface with a UART device

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#235]
**Actual Behaviour.**  

Since NeuroLab devices are in prototype, not every developer gets access to one. But that wouldn't stop us from building the interfaces. I would be suggesting a workaround to implement the necessary code to interface a UART device with NeuroLab Android app.

While porting the app, we have used the same classes that are used for desktop apps. Android USB interface is somewhat different. So we cannot use them. We need to create "Android" code to make it work.

**Expected Behaviour**  

This issue will be solved in following steps.
1. Implement Arduino source code to handle serial messages
2. Implement Java classes in Android to detect, read and write serial messages to a UART port
3. Implement Arduino source code to read a sample neuro data set from an SD card using an SD card module and transmit over a UART channel
4. Improve USB classes in Android app to capture and couple with the existing ported features. 

**Steps to reproduce it**  
> Not available

**Additional context**  
Refer to https://www.allaboutcircuits.com/projects/communicate-with-your-arduino-through-android/ blog post on instructions.

You will need to have;
- Arduino Uno/Mega
- Cables for connectivity

**Would you like to work on the issue?**
@jddeep @suresh-gandhi @ho-dor

**Comment by ho-dor** [comment]
@CloudyPadmal i would like to work on this .This will help me get familiarised with the project completely. Will ask for help if needed . Thanks.

**Comment by CloudyPadmal** [comment]
This issue will be marked completed once #289 is completed

**Comment by CloudyPadmal** [comment]
Interface ready
