### ISSUE TITLE
User Interface for UART testing

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#250]
**Actual Behaviour.**  
App doesn't have a user interface to communicate through the proposed serial connection

**Expected Behaviour**
<img src="https://user-images.githubusercontent.com/14261304/58452892-b405b200-8136-11e9-99bd-5b4d2f8f05b4.png" width="200" />
1. Add a menu item to navigation bar "Test Mode"
2. Create a simple activity with:
    - Two buttons to **Read** and **Write**
    - EditText view to type characters to write
    - TextView to display the read characters
    - Spinner to set baud rates {300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 28800, 38400, 57600, or 115200}
3. Functionality for above views and buttons

**Steps to reproduce it**  
> Not applicable

**Additional context**  
This issue can be break into two pieces and work on it.
- UI implementation
- Code

**Would you like to work on the issue?**
Issue for GSoC

**Comment by jddeep** [comment]
@CloudyPadmal :+1: Would be working on this.
