### ISSUE TITLE
Arduino source code for UART testing

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#251]
**Actual Behaviour.**  
There is no arduino source code to help with the Android UART interface testing

**Expected Behaviour**  
Project need to have a separate directory for the Arduino source code.
1. Create a directory in root folder named `arduino`
2. Create arduino file inside this folder with the source code from https://www.allaboutcircuits.com/projects/communicate-with-your-arduino-through-android/

**Steps to reproduce it**  
> Not applicable

**Additional context**  
In order to close this issue, need to complete the expected behavior and post screen shots of arduino serial terminal with data being sent and received in the PR body.

**Would you like to work on the issue?**
Issue for GSoC

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Would like to work on it.
