### ISSUE TITLE
List down desktop app porting status

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#252]
**Describe the chore**

This Android app is based on source code from NeuroLab desktop app. In order make things fast and accurate, we need to list down all the classes in desktop app and compare if every file is ported and it's done correctly.

Fill in the comment added below this issue with following conditions
  - If the class is ported, prefix the file name with `&#10004;` - &#10004;
  - If the class is not ported yet, prefix the file name with `&#10008;` - &#10008;

Follow this for an example

<pre><font color="#729FCF"><b>.</b></font>
├── <font color="#729FCF"><b>main</b></font>
│   └── <font color="#729FCF"><b>resources</b></font>
│       ├── &#10004; <font color="#8AE234"><b>4colors.jpg</b></font>
│       └── &#10008; <font color="#8AE234"><b>yantra_white.png</b></font>
└── <font color="#729FCF"><b>org</b></font>
    └── <font color="#729FCF"><b>neurovillage</b></font>
        ├── <font color="#729FCF"><b>gui</b></font>
        │   ├── <font color="#8AE234"><b>LongtermAnalyzer.java</b></font>
        └── <font color="#729FCF"><b>tools</b></font>
            ├── &#10008; <font color="#8AE234"><b>BaselineCorrectionFunction.java</b></font>
            └── &#10004; <font color="#8AE234"><b>WindowFunction.java</b></font>
</pre>

**Would you like to work on the issue?**
Issue for GSoC

**Comment by CloudyPadmal** [comment]
<pre><font color="#729FCF"><b>.</b></font>
├── <font color="#729FCF"><b>main</b></font>
│   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#8AE234"><b>4colors.jpg</b></font>
│       ├── <font color="#8AE234"><b>flare.png</b></font>
│       ├── <font color="#8AE234"><b>nforest1.png</b></font>
│       ├── <font color="#8AE234"><b>nforest2.png</b></font>
│       ├── <font color="#8AE234"><b>nforest3.png</b></font>
│       ├── <font color="#8AE234"><b>universe1.png</b></font>
│       ├── <font color="#8AE234"><b>universe2.png</b></font>
│       ├── <font color="#8AE234"><b>universe3.png</b></font>
│       ├── <font color="#8AE234"><b>yantra.png</b></font>
│       └── <font color="#8AE234"><b>yantra_white.png</b></font>
└── <font color="#729FCF"><b>org</b></font>
    └── <font color="#729FCF"><b>neurovillage</b></font>
        ├── <font color="#729FCF"><b>gui</b></font>
        │   ├── <font color="#8AE234"><b>LongtermAnalyzer.java</b></font>
        │   ├── <font color="#8AE234"><b>NFBSettingsWindow.java</b></font>
        │   ├── <font color="#8AE234"><b>SerialForwardMask.java</b></font>
        │   ├── <font color="#8AE234"><b>SpectralViewPanel.java</b></font>
        │   └── <font color="#8AE234"><b>ThresholdRenderer.java</b></font>
        ├── <font color="#729FCF"><b>main</b></font>
        │   ├── <font color="#8AE234"><b>BCISettings.java</b></font>
        │   ├── <font color="#8AE234"><b>CustomOutputStream.java</b></font>
        │   ├── <font color="#8AE234"><b>DataReceiver.java</b></font>
        │   ├── <font color="#8AE234"><b>FakeLock.java</b></font>
        │   ├── <font color="#8AE234"><b>Filter.java</b></font>
        │   ├── <font color="#8AE234"><b>InputInterface.java</b></font>
        │   ├── <font color="#8AE234"><b>Launcher.java</b></font>
        │   ├── <font color="#8AE234"><b>LongtermFeedbackGraph.java</b></font>
        │   ├── <font color="#8AE234"><b>LongtermGraph.java</b></font>
        │   ├── <font color="#8AE234"><b>MathBasics.java</b></font>
        │   ├── <font color="#729FCF"><b>network</b></font>
        │   │   ├── <font color="#8AE234"><b>OSCForwarder.java</b></font>
        │   │   ├── <font color="#8AE234"><b>OSCReceiver.java</b></font>
        │   │   └── <font color="#8AE234"><b>SerialForwarder.java</b></font>
        │   ├── <font color="#8AE234"><b>NeuroUtils.java</b></font>
        │   ├── <font color="#8AE234"><b>NFBGraph.java</b></font>
        │   ├── <font color="#8AE234"><b>NFBServer.java</b></font>
        │   ├── <font color="#729FCF"><b>output</b></font>
        │   │   ├── <font color="#729FCF"><b>audio</b></font>
        │   │   │   ├── <font color="#8AE234"><b>AudioFeedback.java</b></font>
        │   │   │   ├── <font color="#8AE234"><b>FocusAudioFeedback.java</b></font>
        │   │   │   └── <font color="#8AE234"><b>JSynThread.java</b></font>
        │   │   ├── <font color="#729FCF"><b>feedback</b></font>
        │   │   │   └── <font color="#8AE234"><b>Feedback.java</b></font>
        │   │   └── <font color="#729FCF"><b>visual</b></font>
        │   │       ├── <font color="#8AE234"><b>FocusOMeterGLRenderer.java</b></font>
        │   │       ├── <font color="#8AE234"><b>FocusOMeter.java</b></font>
        │   │       ├── <font color="#8AE234"><b>LongtermFFTVisualizer.java</b></font>
        │   │       ├── <font color="#8AE234"><b>NeuroGameRenderer.java</b></font>
        │   │       ├── <font color="#8AE234"><b>NeuroGameVisuals.java</b></font>
        │   │       ├── <font color="#8AE234"><b>OSCFeedback.java</b></font>
        │   │       ├── <font color="#8AE234"><b>ZenSpaceGLRenderer.java</b></font>
        │   │       └── <font color="#8AE234"><b>ZenSpaceVisuals.java</b></font>
        │   ├── <font color="#8AE234"><b>PlaybackStream.java</b></font>
        │   ├── <font color="#8AE234"><b>Recorder.java</b></font>
        │   ├── <font color="#8AE234"><b>SerialPortInterface.java</b></font>
        │   ├── <font color="#8AE234"><b>SerialPortReader.java</b></font>
        │   ├── <font color="#8AE234"><b>SerialRecorder.java</b></font>
        │   └── <font color="#729FCF"><b>task</b></font>
        │       ├── <font color="#8AE234"><b>BinaryFileOutputTask.java</b></font>
        │       ├── <font color="#8AE234"><b>LongtermFeedbackTrackerTask.java</b></font>
        │       ├── <font color="#8AE234"><b>OscForwardTask.java</b></font>
        │       └── <font color="#8AE234"><b>SerialForwardTask.java</b></font>
        ├── <font color="#729FCF"><b>model</b></font>
        │   ├── <font color="#8AE234"><b>Config.java</b></font>
        │   ├── <font color="#8AE234"><b>DataPacket.java</b></font>
        │   ├── <font color="#8AE234"><b>DefaultFFTData.java</b></font>
        │   ├── <font color="#8AE234"><b>FeedbackSettings.java</b></font>
        │   ├── <font color="#8AE234"><b>FFTData.java</b></font>
        │   ├── <font color="#8AE234"><b>FFTPreprocessor.java</b></font>
        │   ├── <font color="#8AE234"><b>FileOutputTask.java</b></font>
        │   ├── <font color="#8AE234"><b>FocusFeedbackSettings.java</b></font>
        │   ├── <font color="#8AE234"><b>GenericFeedbackSettings.java</b></font>
        │   ├── <font color="#8AE234"><b>NFBProcessor.java</b></font>
        │   ├── <font color="#8AE234"><b>OSCForwardMask.java</b></font>
        │   ├── <font color="#8AE234"><b>RelaxFeedbackSettings.java</b></font>
        │   └── <font color="#8AE234"><b>Task.java</b></font>
        └── <font color="#729FCF"><b>tools</b></font>
            ├── <font color="#8AE234"><b>BaselineCorrectionFunction.java</b></font>
            ├── <font color="#8AE234"><b>ColorMap.java</b></font>
            ├── <font color="#8AE234"><b>ResourceManager.java</b></font>
            ├── <font color="#8AE234"><b>Utils.java</b></font>
            └── <font color="#8AE234"><b>WindowFunction.java</b></font>
</pre>

**Comment by suresh-gandhi** [comment]
.
├── main
│   └── resources
│       ├── 4colors.jpg
│       ├── flare.png
│       ├── nforest1.png
│       ├── nforest2.png
│       ├── nforest3.png
│       ├── universe1.png
│       ├── universe2.png
│       ├── universe3.png
│       ├── yantra.png
│       └── yantra_white.png
└── org
    └── neurovillage
        ├── gui
        │   ├── LongtermAnalyzer.java
        │   ├── NFBSettingsWindow.java
        │   ├── SerialForwardMask.java
        │   ├── SpectralViewPanel.java
        │   └── ThresholdRenderer.java
        ├── main
        │   ├── BCISettings.java
        │   ├── CustomOutputStream.java
        │   ├── DataReceiver.java
        │   ├── FakeLock.java
        │   ├── Filter.java
        │   ├── InputInterface.java
        │   ├── Launcher.java
        │   ├── LongtermFeedbackGraph.java
        │   ├── LongtermGraph.java
        │   ├── MathBasics.java
        │   ├── network
        │   │   ├── OSCForwarder.java
        │   │   ├── OSCReceiver.java
        │   │   └── SerialForwarder.java
        │   ├── NeuroUtils.java
        │   ├── NFBGraph.java
        │   ├── NFBServer.java
        │   ├── output
        │   │   ├── audio
        │   │   │   ├── AudioFeedback.java
        │   │   │   ├── FocusAudioFeedback.java
        │   │   │   └── JSynThread.java
        │   │   ├── feedback
        │   │   │   └── Feedback.java
        │   │   └── visual
        │   │       ├── FocusOMeterGLRenderer.java
        │   │       ├── FocusOMeter.java
        │   │       ├── LongtermFFTVisualizer.java
        │   │       ├── NeuroGameRenderer.java
        │   │       ├── NeuroGameVisuals.java
        │   │       ├── OSCFeedback.java
        │   │       ├── ZenSpaceGLRenderer.java
        │   │       └── ZenSpaceVisuals.java
        │   ├── PlaybackStream.java
        │   ├── Recorder.java
        │   ├── SerialPortInterface.java
        │   ├── SerialPortReader.java
        │   ├── SerialRecorder.java
        │   └── task
        │       ├── BinaryFileOutputTask.java
        │       ├── LongtermFeedbackTrackerTask.java
        │       ├── OscForwardTask.java
        │       └── SerialForwardTask.java
        ├── model
        │   ├── Config.java
        │   ├── DataPacket.java
        │   ├── DefaultFFTData.java
        │   ├── FeedbackSettings.java
        │   ├── FFTData.java
        │   ├── FFTPreprocessor.java
        │   ├── FileOutputTask.java
        │   ├── FocusFeedbackSettings.java
        │   ├── GenericFeedbackSettings.java
        │   ├── NFBProcessor.java
        │   ├── OSCForwardMask.java
        │   ├── RelaxFeedbackSettings.java
        │   └── Task.java
        └── tools
            ├── BaselineCorrectionFunction.java
            ├── ColorMap.java
            ├── ResourceManager.java
            ├── Utils.java
            └── WindowFunction.java

**Comment by suresh-gandhi** [comment]
@CloudyPadmal Is this the correct way to do it? 
```
.
├── main
│   └── resources
│       ├── ✘ 4colors.jpg
│       ├── ✘ flare.png
│       ├── ✘ nforest1.png
│       ├── ✘ nforest2.png
│       ├── ✘ nforest3.png
│       ├── ✘ universe1.png
│       ├── ✘ universe2.png
│       ├── ✘ universe3.png
│       ├── ✘ yantra.png
│       └── ✘ yantra_white.png
└── org
    └── neurovillage
        ├── gui
        │   ├── ✘ LongtermAnalyzer.java
        │   ├── ✘ NFBSettingsWindow.java
        │   ├── ✘ SerialForwardMask.java
        │   ├── ✔ SpectralViewPanel.java
        │   └── ✔ ThresholdRenderer.java
        ├── main
        │   ├── ✔ BCISettings.java
        │   ├── ✔ CustomOutputStream.java
        │   ├── ✔ DataReceiver.java
        │   ├── ✔ FakeLock.java
        │   ├── ✔ Filter.java
        │   ├── ✔ InputInterface.java
        │   ├── ✔ Launcher.java
        │   ├── ✘ LongtermFeedbackGraph.java
        │   ├── ✔ LongtermGraph.java
        │   ├── ✔ MathBasics.java
        │   ├── network
        │   │   ├── ✔ OSCForwarder.java
        │   │   ├── ✔ OSCReceiver.java
        │   │   └── ✔ SerialForwarder.java
        │   ├── ✔ NeuroUtils.java
        │   ├── ✔ NFBGraph.java
        │   ├── ✔ NFBServer.java
        │   ├── output
        │   │   ├── audio
        │   │   │   ├── ✔ AudioFeedback.java
        │   │   │   ├── ✔ FocusAudioFeedback.java
        │   │   │   └── ✔ JSynThread.java
        │   │   ├── feedback
        │   │   │   └── ✔ Feedback.java
        │   │   └── visual
        │   │       ├── ✔ FocusOMeterGLRenderer.java
        │   │       ├── ✔ FocusOMeter.java
        │   │       ├── ✔ LongtermFFTVisualizer.java
        │   │       ├── ✔ NeuroGameRenderer.java
        │   │       ├── ✔ NeuroGameVisuals.java
        │   │       ├── ✘ OSCFeedback.java
        │   │       ├── ✔ ZenSpaceGLRenderer.java
        │   │       └── ✔ ZenSpaceVisuals.java
        │   ├── ✔ PlaybackStream.java
        │   ├── ✔ Recorder.java
        │   ├── ✔ SerialPortInterface.java
        │   ├── ✔ SerialPortReader.java
        │   ├── ✔ SerialRecorder.java
        │   └── task
        │       ├── ✔ BinaryFileOutputTask.java
        │       ├── ✔ LongtermFeedbackTrackerTask.java
        │       ├── ✔ OscForwardTask.java
        │       └── ✔ SerialForwardTask.java
        ├── model
        │   ├── ✔ Config.java
        │   ├── ✘ DataPacket.java
        │   ├── ✔ DefaultFFTData.java
        │   ├── ✔ FeedbackSettings.java
        │   ├── ✔ FFTData.java
        │   ├── ✔ FFTPreprocessor.java
        │   ├── ✔ FileOutputTask.java
        │   ├── ✔ FocusFeedbackSettings.java
        │   ├── ✔ GenericFeedbackSettings.java
        │   ├── ✔ NFBProcessor.java
        │   ├── ✔ OSCForwardMask.java
        │   ├── ✔ RelaxFeedbackSettings.java
        │   └── ✔ Task.java
        └── tools
            ├── ✔ BaselineCorrectionFunction.java
            ├── ✔ ColorMap.java
            ├── ✔ ResourceManager.java
            ├── ✔ Utils.java
            └── ✔ WindowFunction.java
```

**Comment by suresh-gandhi** [comment]
@jddeep Could you verify once please?

**Comment by CloudyPadmal** [comment]
Yes this is what I wanted. Thanks @suresh-gandhi :+1:

**Comment by CloudyPadmal** [comment]
I think those images are already there in the Android repo right?

**Comment by jddeep** [comment]
> @jddeep Could you verify once please?

Yes this looks fine :+1:  The DataPacket class is empty in the Desktop repo by the way.

**Comment by jddeep** [comment]
> I think those images are already there in the Android repo right?

No @CloudyPadmal They aren't there currently. We have used different resources/images till now.
