### ISSUE TITLE
Club Settings and Feedback Settings together as they have the same purpose

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#263]
**Describe the bug**
Currently, there are two options (and two activities subsequentially) in the settings menu namely **Settings** and **FeedbackSettings** devoted for the same purpose nearly, the former for editing the values and the later for displaying the values.

edit: Also merge "Configurations" into "Settings" and have them as two separate setting groups instead.

**Expected Behaviour**
It doesn't look that professional and appealing and therefore they should be clubbed together into a single **Settings** activity screen.

**Would you like to work on the issue?**
Would like to work on this.

**Comment by CloudyPadmal** [comment]
| Three Configs | Configurations | Settings | Feedback Settings |
| ------------------ | ------------------ | ---------- | ------------------------ |
| <img src="https://user-images.githubusercontent.com/14261304/58545161-55b4fe00-8220-11e9-8acb-a704b84fefc1.png" height=250 /> | <img src="https://user-images.githubusercontent.com/14261304/58545162-55b4fe00-8220-11e9-905f-34ce6b2d4711.png" height=250 /> | <img src="https://user-images.githubusercontent.com/14261304/58545163-55b4fe00-8220-11e9-8364-f11548a606b9.png" height=250 /> | <img src="https://user-images.githubusercontent.com/14261304/58545311-9f9de400-8220-11e9-96df-90b1e147d27a.png" height=250 /> |

**Comment by CloudyPadmal** [comment]
Fixed in #270
