### ISSUE TITLE
nav drawer logo image needs an update

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#278]
**Actual Behaviour.**  
* The current image type is not a vector graphic.
* The app logo on the nav drawer doesn't match with the current theme of the app as it was designed taking into the account the previous theme.

**Expected Behaviour**  
* A matching (with the app theme) vector graphic logo in the navigation drawer.

**Steps to reproduce it**  
* Open the app.
* Open the nav drawer and look at the logo at the top.

**Screenshot of the current nav drawer logo**:
<img src = "https://user-images.githubusercontent.com/22399995/58863773-17608880-86d1-11e9-878a-bd241c6e9c22.jpg" height = 500>

**Would you like to work on the issue?**
@ho-dor @jddeep

**Comment by suresh-gandhi** [comment]
@ho-dor you even added the previous logo right. Could you please make the required changes.

**Comment by jddeep** [comment]
Alright, I would be doing the necessary change.

**Comment by adityastic** [comment]
@suresh-gandhi @jddeep Let me design something for neurolab.

**Comment by jddeep** [comment]
> @suresh-gandhi @jddeep Let me design something for neurolab.

Cool. I am looking for a circular logo for our app. You can design one and make a PR with the same in the drawable folder. @adityastic Can you do this before evening. I would be integrating it in our app after that tonight.

**Comment by adityastic** [comment]
@jddeep definitely. I'll be posting images here, stay tuned

**Comment by adityastic** [comment]
@jddeep @suresh-gandhi what is the color scheme of the app? Is it going to match pslab?

**Comment by jddeep** [comment]
@adityastic Have a look at the current version of the app. Take some inspiration of color scheme from the splash screen image as well.

**Comment by adityastic** [comment]
With Inspiration from splash screen
<img src="https://user-images.githubusercontent.com/11988517/58850664-2b928e80-86ad-11e9-8539-f595dbc25315.png" width="300" />

**Comment by jddeep** [comment]
Seems nice enough from my side. :+1: Will be waiting till evening for other devs if they have any more suggestions. Thanks for this design @adityastic

**Comment by adityastic** [comment]
Without the Inspiration from Splash Screen, we can change the colors anytime:
<img src="https://user-images.githubusercontent.com/11988517/58850858-ea4eae80-86ad-11e9-83e7-89fd31457b7c.png" width="300"/><img src="https://user-images.githubusercontent.com/11988517/58850859-eb7fdb80-86ad-11e9-93e3-6afb1c1b9eb7.png" width="300"/>

**Comment by adityastic** [comment]
@jddeep @suresh-gandhi @CloudyPadmal Confirm the color scheme. Also if you want more designs, I can create some more :)

**Comment by jddeep** [comment]
The Color scheme seems fine.

**Comment by suresh-gandhi** [comment]
@adityastic you create good designs man. Keep it up. It's fine from my side. 👍

**Comment by adityastic** [comment]
@suresh-gandhi thanks for the wise words :)

**Comment by suresh-gandhi** [comment]
@adityastic can you also design one named logo or something like that for our nav drawer (something like NL written over). You can look at the screenshot (which I forgot to add yesterday :P) above. NL logo looks not that appealing and isn't matching very well with the color scheme. Are you getting what I am saying?

**Comment by adityastic** [comment]
Let's design the app icon and place it in the navdrawer?. That's what we did for badge magic, you can see it's icon as it was designed by me

**Comment by jddeep** [comment]
@adityastic Nice work. We can use the design related to the splash screen for our logo here as we also have to keep the consistent branding of neuro lab. @suresh-gandhi I would suggest keeping the nav-drawer icon clean with only-image. "NL" over the icon isn't so appealing and professional to me (opinion). @suresh-gandhi Thoughts?

**Comment by suresh-gandhi** [comment]
@jddeep yeah I mean. Needs to be simple and appropriate not very complex. Refer to the discussion in [this](https://github.com/fossasia/neurolab-android/pull/233) PR.

**Comment by jddeep** [comment]
Okay, if that is the desire..then @adityastic use the design created as a light watermark kind of thing as background, with a much prominent "NL" at the forefront. Would be simple as well.

**Comment by adityastic** [comment]
@jddeep @suresh-gandhi how about an atom? It would look better than a NL symbol

**Comment by suresh-gandhi** [comment]
@adityastic yeah..we can try that. show the design once.

**Comment by adityastic** [comment]
@sudheesh001 @jddeep a bit of translucency in image, and a simple gradient. views? 

<img src="https://user-images.githubusercontent.com/11988517/58893552-06823800-870e-11e9-9e97-fe45445338cf.jpg" width="400" />

**Comment by suresh-gandhi** [comment]
@adityastic good to go from my side. thanks

**Comment by adityastic** [comment]
@jddeep

**Comment by jddeep** [comment]
Yes 👍 from my side. You can make a PR. Thanks.
