### ISSUE TITLE
Missing Program Mode Icon assets (image resources)

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#280]
**Describe the issue**

Missing Program Mode Icon assets (image resources). 

Make a PR with the 4 image resources in the drawable folder.
These images are required in the launcher screen.

**Would you like to work on the issue?**
@jddeep @adityastic

**Comment by adityastic** [comment]
Yes sure

**Comment by adityastic** [comment]
@jddeep @suresh-gandhi @CloudyPadmal Ok So, I have something:

![tempneuro](https://user-images.githubusercontent.com/11988517/58932567-dd02f400-8781-11e9-8978-966263f77aeb.jpg)

This is how a single card should look as per me. PS: I have redesigned the complete app to achieve it. Drop your suggestions below
**NOTE**
Designing every card is a long process, and will take almost 2-3 hrs for a single card.

**Comment by adityastic** [comment]
@jddeep @suresh-gandhi I have completely redesigned the app from scratch.

**Comment by jddeep** [comment]
@adityastic Make a PR with only drawable resources like the 4 icons and the background one. Nice work on the background image.

**Comment by adityastic** [comment]
@jddeep you might need more than that. The Background is not a single image, It has a base which is attached with the image and another layout which acts as an actual background to the card.

**Comment by jddeep** [comment]
@adityastic Where have you designed it? Adobe XD?

**Comment by adityastic** [comment]
@jddeep It is not a mockup xD. It is an actual working application. I just took a screenshot

**Comment by adityastic** [comment]
> @adityastic Where have you designed it? Adobe XD?

Yes. I specialise in Design and Custom UI/UX in Android. Self Taught haha

**Comment by jddeep** [comment]
Nice work. So i am guessing it is not in our actual app. You have made this in a sample app?

**Comment by adityastic** [comment]
@jddeep I just made the changes directly to neurolab xD

**Comment by jddeep** [comment]
Ah! Okay cool. So do one thing. Push the changes to your fork. I will have a look there. After that we can work on a PR. @adityastic

**Comment by adityastic** [comment]
@jddeep sure. I will need another 6-8 hrs for the rest of the icons. But im not sure If I will be able to work that long, I have to take care of badge magic as well

**Comment by adityastic** [comment]
I'll push the changes to my fork, have a look with this single card. Make changes to your pr accordingly, till then I can get the next Cards Designed

**Comment by jddeep** [comment]
@adityastic Just push the "Focus" card change. I will take it from there. No worries.

**Comment by suresh-gandhi** [comment]
@adityastic looking great 👍  Yeah go ahead and push it to the fork. Will see the remaining then.

**Comment by adityastic** [comment]
https://github.com/adityastic/neurolab-android. I have removed the complete redesign from this commit, just the card changes with the font. Good luck, dont forget to credit me in the app :)

**Comment by adityastic** [comment]
Ill make the rest of icons soon, next card probably by evening

**Comment by adityastic** [comment]
Another Update, Suggestions? @CloudyPadmal @iamareebjamal @jddeep @suresh-gandhi 

<img src="https://user-images.githubusercontent.com/11988517/59013165-f629a480-8856-11e9-9442-768bfc7e2dfd.jpg" width=300/>

**Comment by CloudyPadmal** [comment]
@adityastic , are these vector graphics?

**Comment by jddeep** [comment]
Yeah @CloudyPadmal they are.

**Comment by jddeep** [comment]
@adityastic Make a PR with the relax icon and background directed to fix this issue. Thanks.

**Comment by jddeep** [comment]
Also we will be having one more card named 'Memory Graphs'. Make a card for that and make the PR including images for that also.

**Comment by adityastic** [comment]
@CloudyPadmal Yep. But didn't export them to the app as vectors yet, just used as png for now. Vectors is what I will give when finalizing the pr

**Comment by adityastic** [comment]
@jddeep I need information regarding the rest of the 2 icons, named VJ and Serial. Explain them briefly to me plz

**Comment by adityastic** [comment]
@jddeep alright, explain me about the use cases of memory graphs as well plz
