### ISSUE TITLE
Remove OTF files and use font provider

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/neurolab-android#283]
Don't unnecessarily bloat the apk. Just use the font provider in Android

**Comment by jddeep** [comment]
Okay. Will fix that.

**Comment by suresh-gandhi** [comment]
@jddeep could you fix this by today.

**Comment by iamareebjamal** [comment]
Only half issue is solved

**Comment by jddeep** [comment]
> Only half issue is solved

@iamareebjamal we are currently using default fonts. We had those otf files and the string res of the same for additional usage or usage in the near future. We didn't use them.
