### ISSUE TITLE
Datasets for EEG testing

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#288]
**Describe the issue**

We need more data to implement features. Best way for now is to look for free and open datasets recorded by researchers and use it in our app. Repository https://github.com/meagmohit/EEG-Datasets contains a set of public data sets.

This issue is to pick the appropriate ones related to EEG and prepare those data sets to feed into NeuroLab through Arduino interface

Task: Pick 10 different data sets from the above mentioned repository and pre-process them to match with our hardware interface

**Would you like to work on the issue?**

Issue for GSoC
@jddeep and @suresh-gandhi please pick 5 each and list the headings under this issue (to avoid duplicates). After that, create a folder in repo root and add pre-processed data. Set priority to recognized datasets. (eg: MNIST, OpenBCI etc...). Limit the pre-processed data set to be under 25MB. Format would be the same as the sample dataset we have in repo.

| time | data | data (if available) |
| ----- | ------ | ------ | 
| ttttt | 4526.24544 ... | 4952.11555 ... |
| ttttt | 4526.24544 ... | 4952.11555 ... |
| ... | ... | ... |
| ttttt | 4526.24544 ... | 4952.11555 ... |

**Comment by jddeep** [comment]
Datasets I am working with : 
1. **NeuroMarketing**:
Contains Data for 25 subjects.
2. **MNIST** (MindBigData)
Containing data sets of MindWave, Muse, Insight.
3. **[DEAP](http://www.eecs.qmul.ac.uk/mmv/datasets/deap/)**
4. **[IMAGENET Brain](http://www.mindbigdata.com/opendb/imagenet.html)**
5. **[Meditation-EEG-Data](https://www.kaggle.com/abyssjumper/meditation-eegdata)**

**Comment by jddeep** [comment]
> Datasets I am working with :
> **NeuroMarketing**:
> Contains Data for 25 subjects.
> **MNIST** (MindBigData)
> Containing data sets of MindWave, Muse, Insight.

@CloudyPadmal Is this a correct way to mention here?

**Comment by CloudyPadmal** [comment]
Yes. Try to pick 3 more. We need 10 sets in total.

**Comment by suresh-gandhi** [comment]
* [BCI-NER Challenge](https://www.kaggle.com/c/inria-bci-challenge) / [BCI Competition IV-1](http://www.bbci.de/competition/iv/#dataset1)
* [EID-M, EID-S](https://drive.google.com/drive/folders/1t6tL434ZOESb06ZvA4Bw1p9chzxzbRbj)
* [Confused Student EEG brainwave data](https://www.kaggle.com/wanghaohan/confused-eeg)
* [EEG Analysis - Sleep Pattern Detection](https://www.kaggle.com/jbouv27/eeg)
* [EEG Brainwave dataset of mental State - Relaxed, Neutral, Concentrated || Muse Headset](https://www.kaggle.com/birdy654/eeg-brainwave-dataset-mental-state)
[EEG Brainwave dataset - Feeling Emotions + and - || Muse Headset](https://www.kaggle.com/birdy654/eeg-brainwave-dataset-feeling-emotions)
@CloudyPadmal Is it workable if I take _CC0: public domain_ licensed datasets from kaggle as well. I found them somewhat more related and relevant to our project.
