### ISSUE TITLE
Import and Export data functionality in program modes

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#300]
**Actual Behaviour.**  
Missing Import and Export data functionality in program modes.

**Expected Behaviour**  
Import and Export data functionality in program modes.
- [ ] Focus Mode
- [ ] Relax Mode
- [x] Memory Graph 

**Additional context**  
> Not available

**Would you like to work on the issue?**
Issue for GSOC 2019 Milestone 4

**Comment by jddeep** [comment]
@CloudyPadmal In the importing data, should the files be in CSV format?

**Comment by CloudyPadmal** [comment]
Yes, CSV is the common format. Let's use it in our app.

**Comment by jddeep** [comment]
Okay, will make a PR by today. Thanks.
