### ISSUE TITLE
Add bluetooth connectivity to receive data

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#305]
**Describe the issue**

Current app supports only USB to feed in data. We need an option to connect using a bluetooth module (HC-05/06). Android app should;
- Search for bluetooth device to connect
- Establish connection with bluetooth device
- Receive data from bluetooth module

**Would you like to work on the issue?**

Issue for GSoC. @jddeep @suresh-gandhi who would like to take this up?

**Comment by suresh-gandhi** [comment]
@CloudyPadmal I would like to work on this issue. I have ordered the module as well.
