### ISSUE TITLE
Parse receiving neuro data and plot brainwave frequencies

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#308]
**Describe the issue**

Currently we are getting a raw data feed. This set needs to be processed through ported java functions from desktop and provide user with a visual output.

1. Show graph in MemoryGraph tool
2. Provide statistical output as follows
<img src="https://user-images.githubusercontent.com/14261304/59561694-b7f36880-9040-11e9-954f-24938b237ceb.png" width=200 />

**Would you like to work on the issue?**

Issue for GSoC.

**Comment by jddeep** [comment]
Will be looking into this.
