### ISSUE TITLE
Implement a new section for meditation

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#309]
**Describe the issue**

Neuro devices support meditation and provide feedback to see how well we perform. Similar to muze app, add a new card view "Meditation" and implement a similar UI as follows;

| Types | Results |
| ------ | ------- |
| ![Types](https://user-images.githubusercontent.com/14261304/59561796-07866400-9042-11e9-9812-3f966ddbe83c.png) | ![Results](https://user-images.githubusercontent.com/14261304/59561795-06edcd80-9042-11e9-99f9-168a98fee57e.png) |

No need of stats part

What we expect from this issue is;
- Create a new entry "Meditation"
- Once user enters it, he will get a list of meditations
- Once one is selected, it will provide instructions and play relevant music (Do as a separate issue)
- Display brainwaves and show thresholds of calmness as an overlay

**Would you like to work on the issue?**

Issue for GSoC

**Comment by jddeep** [comment]
Currently, we dont have resources for implementing the Meditation mode fully. We have the basic structure ready for each screen in it that would be fully functional in the future.
We will be hiding this program mode in the app as well for now.
Directed by - @mariobehling
