### ISSUE TITLE
Meditation Card View on the Main Screen

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#321]
**Actual Behaviour**
No meditation card view on the main screen.

**Expected Behaviour**
A meditation card view having similar designs to other program modes.

**Would you like to work on the issue?**
@adityastic could you help

**Comment by suresh-gandhi** [comment]
@adityastic There is a new program mode (similar to focus, relax, etc) named Meditation. Would it be possible for you to design a nice Meditation Card View just like other program modes whenever you get the time? Meanwhile, I am working on mode implementation.

**Comment by adityastic** [comment]
Definitely. Can I do it tomorrow?

**Comment by suresh-gandhi** [comment]
@adityastic sure. Thanks for the help.

**Comment by jddeep** [comment]
Fixed in #327 . Closing this.
