### ISSUE TITLE
improve package structure

### ISSUE THREAD

**Issue by adityastic** [fossasia/neurolab-android#326]
**Describe the bug**
classes are not managed properly. gui contains some core classes. whereas almost all the files are stored in main. Why?, even utils are stored in main. Its difficult to find activities.
One activity lies in a completely different package, program-modes. This will result in the code being not maintainable. 
<img width="305" alt="Screenshot 2019-06-25 at 11 58 06 AM" src="https://user-images.githubusercontent.com/11988517/60074571-d8a67700-9740-11e9-9b12-049e62ae0bad.png">

**Would you like to work on the issue?**
@jddeep @suresh-gandhi take care of it

**Comment by CloudyPadmal** [comment]
I think there are some classes we wouldn't be needing anymore as everything is ported from desktop app and some classes are specific to desktop (Serial communication related stuff etc). Please remove those redundant classes when addressing this issue. Thanks.
