### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by CloudyPadmal** [fossasia/neurolab-android#329]
**Describe the issue**

Screenshots and content in readme file is bit out dated. Need to update with latest changes

**Would you like to work on the issue?**

Issue for GSoC students or new students

**Comment by knightcube** [comment]
May I work on this issue?

**Comment by jddeep** [comment]
@knightcube Welcome! Go ahead :+1: Be sure to update the external library dependencies as well in the readme.

**Comment by knightcube** [comment]
Sure. I will also be making a new Screenshots folder to put all the screenshots at one place
