### ISSUE TITLE
Missing Play or Resume feature in Memory Graph

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#332]
**Actual Behaviour.**  
Missing Play or Resume feature in Memory Graph.

**Expected Behaviour**  
There should be a Play or Resume feature in Memory Graph.

**Steps to reproduce it**  
Go to Memory graph, import data and observe.

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes, would work on it.

**Comment by CloudyPadmal** [comment]
We'll get this feature quickly as a continuation of #331 :+1:

**Comment by jddeep** [comment]
@CloudyPadmal Yup would be doing it today only asap. 👍
