### ISSUE TITLE
Update the Focus Mode Animation

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#347]
**Actual Behaviour.**  
The current focus mode animation needs to be changes.

**Expected Behaviour**  
Implementation needs to be similar of that of desktop.
Reference: 
https://giphy.com/gifs/9MIlg66ykFVcW2HZBM

**Steps to reproduce it**  

**Additional context**  
> Make it similar to desktop

**Would you like to work on the issue?**
@CoderVishalSehgal

**Comment by vishal-sehgal** [comment]
Hey @jddeep, yes I will build something similar to this :)
