### ISSUE TITLE
Fix the getMedian() method of MathBasics class for odd length inputs.

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#35]
**Actual Behaviour**
getMedian() method in MathBasics class doesn't give the correct answer for an input array of odd length. Instead, it returns the (median + 1)th element after arranging the input in ascending order.

**Expected Behaviour**
The method should return the correct median values for all possible inputs.

**Steps to reproduce it**
1. Inside the MainActivity in the OnCreate() method add the following lines of code (temporarily) at the last inorder to test the getMedian() method ->
```
double[] arr = {4.5d, 2.3d, 1.0d};
double median = MathBasics.getMedian(arr);
Log.d("MAINACTIVITY", "the median of the given input array - {4.5d, 2.3d, 1.0d} is " + Double.toString(median));
```
2. After this use the Logcat to see the log messages (set filters appropriately for faster searching).

**LogCat for the issue**
2019-02-03 21:53:32.583 5267-5267/io.neurolab D/MAINACTIVITY: **the median of the given input array - {4.5d, 2.3d, 1.0d} is 4.5**

The median isn't 4.5 but 2.3 for the given array. 4.5 is the third element or the (median + 1)th element which the code wrongly outputs.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by CloudyPadmal** [comment]
Sure @suresh-gandhi , send us a PR to review. Thanks :+1:
