### ISSUE TITLE
Missing ActionBar in FeedbackSettings

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#37]
**Actual Behaviour** There is no action bar present in the activity.

**Expected Behaviour**
There should be an Actionbar/Toolbar

**Steps to reproduce it**
Build and run the app.
Go to Feedback Settings from the drop-down menu.

**Would you like to work on the issue?**
Yes, I would like to work on this issue.

**Comment by jddeep** [comment]
@CloudyPadmal Should I start working on the issue?

**Comment by jddeep** [comment]
@mariobehling @CloudyPadmal can I start working on the issue?

**Comment by jddeep** [comment]
@CloudyPadmal can I start working on the issue?

**Comment by CloudyPadmal** [comment]
Yes you may
