### ISSUE TITLE
PIN layout options in launcher screen

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#397]
**Actual Behaviour.**  
Missing PIN layout options in launcher screen.

**Expected Behaviour**  
PIN layout options in launcher screen.

**Steps to reproduce it**  
> Not available

**Additional context**  
> Not available

**Would you like to work on the issue?**
Yes

**Comment by jddeep** [comment]
@CloudyPadmal Can you please tell where can we find the pin layout diagrams similar to that of PSLab? Maybe we can set up the basic layouts if not the detailed pin descriptions for now.

**Comment by CloudyPadmal** [comment]
Images can be found here https://github.com/fossasia/neurolab-hardware
