### ISSUE TITLE
Configure Focus animation according to data and update speed

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#406]
**Describe the bug**
Currently, the rocket animation uses a linear interpolator. We can have a acceleration one for going up, and slow it down while coming back.

**Expected Behavior**
Configure Focus animation according to data and update speed

**Steps to reproduce it**
N/A

**LogCat for the issue**
N/A

**Would you like to work on the issue?**
@adityastic @jddeep

**Comment by adityastic** [comment]
Dw, I'll take care of it. Let me finish with travis for pslab-desktop

**Comment by CloudyPadmal** [comment]
I think here we have a misunderstanding. The rocket should follow brainwave signal intensities.

1. Fetch raw data. These will be just numbers (probably in between say 3500 - 5000)
2. Process the data to extract frequency components. (alpha, beta etc..)
3. Move the rocket location relative to these frequency intensities. (There won't be sudden changes in brainwaves therefore rocket wouldn't jump)

@jddeep @adityastic are these factors taken into consideration here? Issue title seems right but the description seems to say something else. **Rocket movement depends on processed data**.

**Comment by jddeep** [comment]
@CloudyPadmal Yes, that data has been processed to get a set of frequency values and we are using those values for the animation. Higher frequency values -> gamma -> more concentration...rocket moves up and faster, Lower values -> alpha -> relaxing...rocket moves down slowly.
And coming to the animation and the jumping (as it seems), we need to configure the android animation accordingly. But no issues, as the data it would be using is processed only. We would be finalizing the animation in a bit.
