### ISSUE TITLE
Link a media seekbar and timer to the focus mode animation

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#409]
**Actual Behaviour.**  
Missing Link a media seekbar and timer to the focus mode animation.

**Expected Behaviour**  
Link a media seekbar and timer to the focus mode animation.

**Steps to reproduce it**  
> Not available

**Additional context**  
> N/A

**Would you like to work on the issue?**
@adityastic @jddeep

**Comment by adityastic** [comment]
I'll take it

**Comment by CloudyPadmal** [comment]
@adityastic any update on this?

**Comment by jddeep** [comment]
@CloudyPadmal I'll be making the PR for this. The PR is ready, was waiting for a couple of PRs before this to get merged. Will make the PR by evening.
