### ISSUE TITLE
Brush up the UX/UI and the text messages of the app

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#429]
**Describe the issue**

Brush up the UX/UI and the text messages of the app.

**Would you like to work on the issue?**
Yes

**Comment by rajput2122** [comment]
I want to solve this issue. can you please tell me some brief about the layout which UI/UX to be improved mainly. I want to contribute

**Comment by jddeep** [comment]
@rajput2122 There are some UI improvements along with some UX updates which will require a bit time to understand the codebase. Feel free to fork this project, and go through the codebase and have an understanding of things. New issues will be opened soon and you can start contributing to them and even participate in [Codeheat 2019](https://codeheat.org).

**Comment by rajput2122** [comment]
Thank you, sir,codeheat applications are closed now. when will applications for codeheat 2020 start?

**Comment by jddeep** [comment]
@rajput2122 Applications will open soon. Keep an eye on the website and announcements here in the [fossasia gitter channel](https://gitter.im/fossasia/fossasia).
