### ISSUE TITLE
App icon for NeuroLab

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#437]
**Actual Behaviour.**  
There is no app icon currently.

**Expected Behaviour**  
There should be an app icon,

**Steps to reproduce it**  
Install the app.

**Additional context**  
N/A

**Would you like to work on the issue?**
Yes

**Comment by rajput2122** [comment]
can i do this sir?

**Comment by jddeep** [comment]
@rajput2122 Alright sure. Have a look at the Navigation drawer of the app and the icon in its header. Make the App icon similar to that. Also, please ensure you resolve this issue and make a PR ASAP. Thanks.

**Comment by rajput2122** [comment]
Done sir. while making PR asking for .apk file is it necessary?

**Comment by jddeep** [comment]
Zip the apk file and attach it in the PR body (upload it). It is needed for testing.

**Comment by rajput2122** [comment]
Done sir.
