### ISSUE TITLE
Back navigation button in app bar to all possible screens

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#445]
**Actual Behaviour.**  
Missing back button in the app bar in some screens.

**Expected Behaviour**  
Check the screens and add the back button.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by dipu989** [comment]
@jddeep I would like to work on this issue!
Please assign this issue to me.

**Comment by jddeep** [comment]
@dipu989  Sure. I'll assign it to you. Note this issue is for [Codeheat 2019](https://codeheat.org) so be sure to register first and make a PR once Codeheat officially starts to get your PR counted for the contest. You can even make a PR now nevertheless. Thanks.

**Comment by dipu989** [comment]
@jddeep  Sure, I have solved the issue and will open the PR once Codeheat starts!

**Comment by rob729** [comment]
@dipu989 Are you still working on this issue?

**Comment by dipu989** [comment]
@rob729  Yes! I am currently working on this.

**Comment by rob729** [comment]
Ok
