### ISSUE TITLE
App closes on clicking back button from Settings screen. 

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#446]
**Actual Behaviour.**  
App closes on clicking back button from Settings screen. 

**Expected Behaviour**  
Make app move back to Home screen.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by anandtushar111** [comment]
Can I work on this?

**Comment by jddeep** [comment]
@anandtushar111 Sure. I'll assign it to you. Note this issue is for [Codeheat 2019](https://codeheat.org) so be sure to register first and make a PR once Codeheat officially starts to get your PR counted for the contest. You can even make a PR now nevertheless. Thanks.

**Comment by anandtushar111** [comment]
I have registered for Codeheat 2019. I have solved this issue.

**Comment by jddeep** [comment]
Thanks. You can definitely make a PR now but it won't get counted for Codeheat contest. To get it evaluated as a Codeheat PR, make it after Codeheat 2019 officially starts. Keep a look at announcements related to Codeheat [here](https://gitter.im/fossasia/fossasia).

**Comment by anandtushar111** [comment]
Okay, sir. I'll make a PR when Codeheat starts.

**Comment by anandtushar111** [comment]
I have removed a line "finish()" below line 276 in neurolab activity in main package.
![Screen Recording 2019-09-13 at 10 22 21 PM](https://user-images.githubusercontent.com/34808961/64880992-39c25480-d677-11e9-8973-ca2c906ed173.gif)

**Comment by rob729** [comment]
@jddeep Is this issue open to work?
If yes, can I work on this?
