### ISSUE TITLE
Relax home screen

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#447]
**Actual Behaviour.**  
Missing relax home screen.

**Expected Behaviour**  
Develop a nice home screen similar to Focus mode.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by kshitiz-kumar** [comment]
I would like to work on this.

**Comment by jddeep** [comment]
Sure @kshitiz-kumar. I'll assign it to you.

**Comment by kshitiz-kumar** [comment]
Also @jddeep I have found an issue with the settings activity.
When the settings is operated in landscape mode the config fragment kind of collapses.
Here is a link to it https://drive.google.com/file/d/1jXshJfR-9-CVH3jrAxF7PZWP7Hj3JHtH/view?usp=sharing

**Comment by jddeep** [comment]
@kshitiz-kumar Most of the screens of the app are not responsive. Please open new issues for different screens as you encounter them. I'll add them to the Codeheat milestone. Then you and other devs can work on it. Thank you.

**Comment by adityastic** [comment]
Need a background 😂

**Comment by jddeep** [comment]
> Need a background

@kshitiz-kumar is assigned on this. If you want you can provide.

**Comment by adityastic** [comment]
@jddeep let him try. I'll design something for sure though xD
