### ISSUE TITLE
Develop the Share feature in the app

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#450]
**Actual Behaviour.**  
Missing Share feature in the app.

**Expected Behaviour**  
Develop the Share feature in the app.

**Steps to reproduce it**  
Check the bottom option in the navigation drawer of the app.

**Additional context**  
By share, we mean sharing a logged/recorded/test dataset to another user's device.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by adityastic** [comment]
I'd like to work on it

**Comment by rob729** [comment]
@adityastic Can I work on this issue as you are already working on other issues?

**Comment by adityastic** [comment]
@rob729 sure, go ahead

**Comment by rob729** [comment]
@jddeep @adityastic Do you have any plan/idea on how to implement this feature?

**Comment by jddeep** [comment]
@rob729 Please read the whole issue description and additional context. Thanks.

**Comment by adityastic** [comment]
> @jddeep @adityastic Do you have any plan/idea on how to implement this feature?

The issue is straightforward, nothing tough. As said by @jddeep issue description should be enough

**Comment by Bhavnaharitsa** [comment]
@jddeep Can I work on this?

**Comment by jddeep** [comment]
> @jddeep Can I work on this?

@rob729 Any updates on this?

**Comment by jddeep** [comment]
@Bhavnaharitsa please wait till @rob729 gives me any updates. Otherwise I will assign this to you.

**Comment by rob729** [comment]
@Bhavnaharitsa  you can work on this issue.

**Comment by nikhil097** [comment]
@Bhavnaharitsa Are you working on this issue?

**Comment by Bhavnaharitsa** [comment]
@nikhil097 Yes, I am. Please find new issues :)

**Comment by AshutoshDas07** [comment]
can i take up this issue?

**Comment by dipu989** [comment]
@Bhavnaharitsa If you are no working on this issue, @jddeep can you assign this to me after confirmation?
Thanks!

**Comment by jddeep** [comment]
@dipu989 Go ahead :+1:
