### ISSUE TITLE
Remove duplicate resources and dimens values

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#453]
**Describe the bug**
Some resource files are redundant in the app codebase and not needed. 
Also, there are duplicate dimens values. Remove them and be sure to make changes wherever the duplicates were used throughout the codebase.

**Expected Behavior**
Remove duplicate resources and dimens values

**Steps to reproduce it**
Go through the resources and codebase of the app.

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by Zyro9922** [comment]
Yes, I want to work on this issue.

**Comment by rajput2122** [comment]
I would like to work on this issue.can u please assign me?

**Comment by jddeep** [comment]
@rajput2122 Sure. I'll assign it to you. Note this issue is for [Codeheat 2019](https://codeheat.org). So be sure to register first and make a PR once Codeheat officially starts to get your PR counted for the contest. You can even make a PR now nevertheless. Thanks.

**Comment by rajput2122** [comment]
Sir can i delete all the jpg and convert all png to vector assets?

**Comment by adityastic** [comment]
@rajput2122 plz. If possible convert raw videos to vector animations also

**Comment by rajput2122** [comment]
@adityastic Sir am i right ? you are saying to change video to gif.

**Comment by adityastic** [comment]
@rajput2122 nope. Not gif, read about animated vectors

**Comment by jddeep** [comment]
@rajput2122 It has been quite some time you got assigned to this issue. Any updates on this?

**Comment by kshitiz-kumar** [comment]
If no one is working on this, please assign it to me.

**Comment by jddeep** [comment]
@kshitiz-kumar Go for it. :+1:

**Comment by CodeMonk263** [comment]
If issue is still open can i work on it?

**Comment by jddeep** [comment]
@kshitiz-kumar I see you are taking up multiple issues at a time. Please select one at a time, address it and then move forward.

**Comment by jddeep** [comment]
> If issue is still open can i work on it?

@CodeMonk263 Yes it is. Would you like to take it up?

**Comment by CodeMonk263** [comment]
Yes

**Comment by CodeMonk263** [comment]
> > If issue is still open can i work on it?
> 
> @CodeMonk263 Yes it is. Would you like to take it up?

Yes

**Comment by jddeep** [comment]
@CodeMonk263 :+1: Send us a PR. We will review it.

**Comment by kshitiz-kumar** [comment]
> @kshitiz-kumar I see you are taking up multiple issues at a time. Please select one at a time, address it and then move forward.

Sure @jddeep

**Comment by CodeMonk263** [comment]
> @CodeMonk263  Send us a PR. We will review it.

Check PR

**Comment by jddeep** [comment]
We can open this later if we require. Thanks.
