### ISSUE TITLE
Load in sample Datasets on App install

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#456]
**Actual Behaviour.**  
If the user doesn't have a device, they can not import datasets into the app.

**Expected Behaviour**  
It may happen many people don't have the device. So as soon they install the app for the first time on their device, a folder called Neurolab gets created in the root internal storage directory with some sample datasets in it.

**Steps to reproduce it**  
Go to Data Logger to import dataset.

**Additional context**  
The datasets are here:
[NeurolabDatasets.zip](https://github.com/fossasia/neurolab-android/files/3584412/NeurolabDatasets.zip)

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by dipu989** [comment]
@jddeep  I would like to work on this issue.

**Comment by jddeep** [comment]
@dipu989 I have given the datasets to be loaded in the Issue description. Use from there.

**Comment by dipu989** [comment]
@jddeep Thanks 👍
