### ISSUE TITLE
Make a Landscape screen for Home/Launcher Screen

### ISSUE THREAD

**Issue by jddeep** [fossasia/neurolab-android#459]
**Actual Behaviour.**  
Home screen not properly responsive. Make a responsive one.

**Expected Behaviour**  
Make a Landscape screen for Home/Launcher Screen.

**Steps to reproduce it**  
See the Home screen.

**Additional context**  
N/A

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by adityastic** [comment]
I'll work on it

**Comment by nikhil097** [comment]
@adityastic Are you still working on it?
I want to work on it.

**Comment by adityastic** [comment]
@nikhil097 didnt get time recently, will work on it this weekend

**Comment by kshitiz-kumar** [comment]
Anyone Working on this ?

**Comment by rob729** [comment]
@jddeep Can I work on this issue?

**Comment by adityastic** [comment]
@rob729 sure

**Comment by CodeMonk263** [comment]
Can i work on this?

**Comment by jddeep** [comment]
@rob729 Any updates on this?

**Comment by rob729** [comment]
<img src = "https://user-images.githubusercontent.com/31350501/66715662-6f2ba080-ede3-11e9-8d91-18d876fc97d4.jpg" width = 300>
@jddeep Is this the layout of which I have to make a landscape layout?

**Comment by rob729** [comment]
> <img alt="" width="300" src="https://user-images.githubusercontent.com/31350501/66715662-6f2ba080-ede3-11e9-8d91-18d876fc97d4.jpg">
> @jddeep Is this the layout of which I have to make a landscape layout?

@jddeep ??

**Comment by jddeep** [comment]
Yes obviously @rob729

**Comment by rob729** [comment]
But there is already a landscape layout of content_main.xml
So what should I do?

**Comment by jddeep** [comment]
Remake it properly.
