### ISSUE TITLE
Add Release Drafter to neurolab

### ISSUE THREAD

**Issue by adityastic** [fossasia/neurolab-android#463]
**Describe the issue**
Add Release Drafter to Neurolab

**Comment by adityastic** [comment]
@CloudyPadmal please add release drafter to this project

**Comment by Abhik1998** [comment]
Can I take this up?

**Comment by jddeep** [comment]
> Can I take this up?

Sure :+1:

**Comment by adityastic** [comment]
@Abhik1998 you need repo access to perform this.

**Comment by Abhik1998** [comment]
Yes more specifically to the .git folder

**Comment by adityastic** [comment]
@Abhik1998 what?. I'm telling you need repo access to add a github app.

**Comment by Abhik1998** [comment]
Yes locally i am testing that. After that I will require the repo access.
