### ISSUE TITLE
onBackPressed calls intent instead of finishing the activity

### ISSUE THREAD

**Issue by jyotirmoy-paul** [fossasia/neurolab-android#468]
## Describe the bug
```onBackPressed``` calls intent instead of finishing the activity, everytime adding a new activity to the activity stack, thus while closing the application the user needs to perform n back presses. This issue can be resolved by not calling intent everytime on back press.

## Expected Behavior
Let's say after opening the ```activities.FocusParentActivity``` if the user presses the back button, instead of calling intent to the ```main.NeuroLab``` activity, the app should just ```finish()``` the current ```FocusParentActivity```, that would automatically make the user return to the ```main.NeuroLab``` activity.

## Steps to reproduce it
* Open the ```main.NeuroLab``` Acitivity, and now open ```activities.FocusParentActivity```
* After the ```FocusParentActivity``` is opened, try pressing back button
* Now instead of closing the ```FocusParentActivity``` the app calls an intent to the ```main.NeuroLab``` activity. This part can be optimized.

## Visuals of the issue
![sample-issue](https://user-images.githubusercontent.com/41543437/65153677-cee29600-da47-11e9-9855-14226be7fb65.gif)

## System Information
<table>
<tr>
  <td>Device</td><td>Xiomi Redmi Note 5 Pro</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Pie 9.0</td>
</tr>
</table>

## Would you like to work on the issue?
I would love to work on the issue.

**Comment by jddeep** [comment]
@jyotirmoy-paul Please go ahead.

**Comment by dipu989** [comment]
@jddeep  I am working on this as a part of issue https://github.com/fossasia/neurolab-android/issues/445.
I have a draft PR regarding this. I will open it tonight.

**Comment by jyotirmoy-paul** [comment]
@dipu989 Oh I thought #445 is about a different issue, well then please go ahead.

**Comment by jddeep** [comment]
@dipu989 Alright. @jyotirmoy-paul Please work on some other issue. Thanks.
