### ISSUE TITLE
Landscape Orientation for Focus Home Screen

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#473]
**Actual Behaviour.**  
Creating a Landscape orientation for focus Home screen.

**Expected Behaviour**  
 Should work properly in Landscape mode

**Steps to reproduce it**  
Similar to the portrait mode.

**Additional context**  
NA

**Would you like to work on the issue?**
Issue for Codeheat.

**Comment by jddeep** [comment]
@kshitiz-kumar Please open landscape issues for all screens in the app. I will assign you to them one by one after resolving them one after other. But, first please open a series of issues so that other devs can also contribute if it suits them. Thank you.
