### ISSUE TITLE
Add In App Update support.

### ISSUE THREAD

**Issue by dipu989** [fossasia/neurolab-android#475]
**Expected Behaviour**  
On App start, there should be a prompt to update the application if newer version is available.

**Steps to reproduce it**  
NA

**Additional context**  
NA

**Would you like to work on the issue?**
Yes

**Comment by dipu989** [comment]
@jddeep, This prompt can made during splash screen or when the home screen launches. We don't have an activity dedicated to splash screen but we have one for home screen.
What do you suggest?
Adding activity for splash then prompting for update or prompting update on home screen?

**Comment by jddeep** [comment]
On Home screen.

**Comment by dipu989** [comment]
@jddeep  Got it. Thank you.
