### ISSUE TITLE
Add delete file feature in Data Logger Screen.

### ISSUE THREAD

**Issue by dipu989** [fossasia/neurolab-android#478]
**Expected Behaviour**  
A delete button should to added beside rename button to delete files.
As of now, we have rename feature there and no delete option. 

**Additional context**  
After adding delete button : -
![Screenshot from 2019-09-24 12-19-15](https://user-images.githubusercontent.com/31280303/65488038-cd8cef80-dec5-11e9-8a13-6288dbf578df.png)

**Would you like to work on the issue?**
Yes.

**Comment by dipu989** [comment]
@jddeep  I would like to work on this issue. Thanks!

**Comment by adityastic** [comment]
@dipu989 go ahead

**Comment by jddeep** [comment]
@dipu989 Please complete your opened PRs first by addressing the reviews. Then you can work on other issues. Thanks.

**Comment by dipu989** [comment]
@jddeep  I am almost done with this issue! Will open related PR only after addressing the previously reviewed PR. No worries!

**Comment by jddeep** [comment]
> @jddeep I am almost done with this issue! Will open related PR only after addressing the previously reviewed PR. No worries!

@dipu989 Please follow best practices. It is always advised to complete an open PR according to reviews by mentors.

**Comment by dipu989** [comment]
@jddeep  Ok, Will keep this in mind from now!

**Comment by tanujkapoor15** [comment]
Hi I'd like to work on this issue. If I do get to work on this, this'll be my first open source contribution.
So, please let me know if I can work on this or not.

**Comment by dipu989** [comment]
@tanujkapoor15  I am currently working on this issue. Please try other open issues.
You can explore the app itself and suggest any new feature and work on that as well.
