### ISSUE TITLE
Landscape Screen for Meditation Activity.

### ISSUE THREAD

**Issue by dipu989** [fossasia/neurolab-android#482]
**Expected Behaviour**  
Adding Landscape Screen in Meditation Activity to make it responsive.

**Steps to reproduce it**  
Switch to Developer mode and then go to Meditation Activity's landscape orientation.

**Additional context**  
NA

**Would you like to work on the issue?**
Yes.

**Comment by dipu989** [comment]
@jddeep @adityastic I would like to work on this issue.

**Comment by CodeMonk263** [comment]
Anyone working on this if not please assign me
