### ISSUE TITLE
Settings Landscape Orientation

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#483]
**Actual Behaviour.**  
Make a Landscape orientation for settings screen

**Expected Behaviour**  
Settings screen should work in Landscape mode.

**Steps to reproduce it**  
Similar to settings portrait mode.

**Additional context**  
NA

**Would you like to work on the issue?**
Yes

**Comment by amilaneni99** [comment]
If this issue is open, I would like to work on it. Thanks.

**Comment by jddeep** [comment]
Sure @amilaneni99 :+1:

**Comment by amilaneni99** [comment]
@jddeep I have created a PR. Please review it. Thanks.

**Comment by rob729** [comment]
@amilaneni99 Are you still working on this issue?

**Comment by rob729** [comment]
@jddeep @CloudyPadmal Can I work on this issue?

**Comment by rob729** [comment]
> @jddeep @CloudyPadmal Can I work on this issue?

@jddeep ??

**Comment by rob729** [comment]
@adityastic Can I work on this issue?

**Comment by adityastic** [comment]
@rob729 sure go ahead
