### ISSUE TITLE
Meditate Activity Bug

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#485]
**Describe the bug**
When the developer mode is selected from settings, the meditation cardview should be visible when we switch to neurolab activity. But either the app has to be closed or the orientation has to change for that to happen.
>>Below is a gif showing the behaviour:

![WhatsAppVideo2019-09-30at24556PM](https://user-images.githubusercontent.com/38812752/65867383-e8fb6d00-e393-11e9-93cd-d29fa7fe95f4.gif)

**Expected Behaviour**
Meditation option should be visible in the main activity immediately after enabling developer  mode in settings activity.

**Steps to reproduce it**
Activity life cycle should be managed properly.

**Would you like to work on the issue?**
YES.

**Comment by kshitiz-kumar** [comment]
@jddeep please review if this is a valid bug.

**Comment by adityastic** [comment]
@kshitiz-kumar go ahead

**Comment by kshitiz-kumar** [comment]
@jddeep should i work on this.

**Comment by jddeep** [comment]
@kshitiz-kumar Go ahead please :+1:

**Comment by jddeep** [comment]
@kshitiz-kumar Are you sure this bug still exists? Please pull the latest upstream changes and check once.

**Comment by kshitiz-kumar** [comment]
@jddeep yes this bug exists. I have pulled the latest upstream changes and still getting the same result.
Just to be sure, I will suggest you check it by yourself and let me know.

**Comment by kshitiz-kumar** [comment]
@jddeep another thing to bring to your notice. Whenever you try to open the Focus Activity or Relax  Activity from the navigation drawer, and then go back to the neurolab activity using the back button, the splash screen always starts.
>>here is a gif for your reference

![WhatsAppVideo2019-10-02at100804P](https://user-images.githubusercontent.com/38812752/66064198-94f2b300-e562-11e9-9cae-c1f0e6f88b07.gif)
<br>

Also every time we go to the neurolab activity , toast showing "developer mode is on" pops up, which should only comes after  enabling it from  settings activity or the first time when we start the app (this is what I feel).
