### ISSUE TITLE
Improve UI of Bluetooth test in developer mode

### ISSUE THREAD

**Issue by ho-dor** [fossasia/neurolab-android#489]
**Actual Behaviour.**  

The UI of bluetooth test is very rudimentary.

**Expected Behaviour**  

A good UI should be there.

**Steps to reproduce it**  

In developer mode, open bluetooth test.

**Additional context**  
![Screenshot_20191002-153328_NeuroLab](https://user-images.githubusercontent.com/37077735/66036125-20038700-e52a-11e9-93c8-8a728f2a2dcd.jpg)

**Would you like to work on the issue?**
Yes.

**Comment by thatfedupguy** [comment]
@jddeep is this issue still open? if yes, please assign it to me.
