### ISSUE TITLE
Navigation Drawer Meditation View

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#493]
**Describe the bug**
Navigation Drawer Meditation view unresponsive
**Expected Behaviour**
Meditation Activity should open form navigation drawer.
**Steps to reproduce it**
Look in Neurolab Activity.

>SCREENSHOT
As can be seen from the gif below , I am trying to open the meditation activity from navigation drawer but it is unresponsive.

![Med](https://user-images.githubusercontent.com/38812752/66227501-e766d780-e6fa-11e9-8b80-f9059172496c.gif)

**Would you like to work on the issue?**
YES

**Comment by kshitiz-kumar** [comment]
@jddeep please look for it and assign it to me.

**Comment by CodeMonk263** [comment]
Can i be assigned on this?

**Comment by jddeep** [comment]
> Can i be assigned on this?

Someone else has found this bug and is already assigned on this. Please find other open issues. Thanks.
