### ISSUE TITLE
Create an apk branch and build apks from Master branch automatically

### ISSUE THREAD

**Issue by mariobehling** [fossasia/neurolab-android#5]
For testing purposes apk builds are very useful. Please create an apk branch and build apks from Master branch automatically.

**Comment by CloudyPadmal** [comment]
Initiated fix with #8 
Waiting for `GITHUB_API_KEY` in Travis CI settings

**Comment by CloudyPadmal** [comment]
`GITHUB_API_KEY` added and fixed with #8
