### ISSUE TITLE
Problem in Rocket Animation

### ISSUE THREAD

**Issue by RohitJain1103** [fossasia/neurolab-android#51]
**Actual Behaviour**

These are the following bugs I found in the Rocket Animation:
* There exists a margin asymmetry of the rocket image view in content_main.xml. Start (Left) Margin - 50dp whereas End (Right) Margin - 33dp.
* The animation duration and the repeat count is directly hardcoded in the moveRocket( ) method of the MainActivity.java instead of using proper global variables.
* Though the repeat count is set to 10 in the code but the rocket actually moves 11 times in both to and fro direction.

**Expected Behaviour**

This should be the expected behavior I suppose:
* Margin should be symmetrical on both the sides (50dp on both the sides).
* There should be proper variables made for the repeat count and the animation duration as the instance variables of the class MainActivity so that it becomes easy to customize their values in the future.
* The repeat count variable should be appropriately named to ensure consistency in the actual behavior and the variable name.

**Would you like to work on the issue?**
Yes I would like to work on this issue.

**Comment by RohitJain1103** [comment]
@mariobehling @CloudyPadmal Can I start working on this issue?

**Comment by CloudyPadmal** [comment]
The animation is not to be like this in the final app. If you have a look at the desktop app, there is a rocket moving and once the device is connected, depending on the mental level, the rocket will move up and down. We can have this implementation as it is for now unless you can suggest any performance improvements which will help our cause. So I'll close this and we'll follow up.
