### ISSUE TITLE
Meditation List contains csv datasets alongwith music tracks.

### ISSUE THREAD

**Issue by dipu989** [fossasia/neurolab-android#510]
**Describe the bug**
Meditation List contains csv datasets with music files.
**Expected Behavior**
Datasets should not appear in meditation list.

**Steps to reproduce bug**

1) Enable developer's mode and then go to mediation activity.
2) Open any meditation genre.

**Screenshots of the issue**
![Screenshot_2019_10_19_12_45_46_64_243bed73eac0221c54c37b9ad745f08a_min__1571470326_52438](https://user-images.githubusercontent.com/31280303/67139701-b8ab3e00-f270-11e9-8e22-c12a08ab0d85.jpg)

**Would you like to work on the issue?**
Yes

**Comment by dipu989** [comment]
@jddeep @CloudyPadmal I would like to resolve this issue. Please assign!

**Comment by adityastic** [comment]
@dipu989 done
