### ISSUE TITLE
Splash Screen triggers from Relax and Focus activity.

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#511]
**Describe the bug**
Whenever the focus or relax activity started from navigation drawer and then we move back to the main activity splash screen opens.

**Expected Behavior**
Splash screen should not trigger every time we move back to main screen and also the toast showing "Developer mode is on" should be managed properly. 

**Steps to reproduce it**
Go to the focus and relax screen from navigation drawer and hit back button.

**Screenshots of the issue**
![splash](https://user-images.githubusercontent.com/38812752/67149195-ebcbec80-f2c5-11e9-853e-e514de429d9f.gif)

**Would you like to work on the issue?**
YES

**Comment by kshitiz-kumar** [comment]
@jddeep please assign it to me.

**Comment by adityastic** [comment]
@kshitiz-kumar go ahead

**Comment by jddeep** [comment]
@kshitiz-kumar updates??

**Comment by kshitiz-kumar** [comment]
@jddeep

**Comment by rob729** [comment]
@jddeep Can I work on this issue?

**Comment by kshitiz-kumar** [comment]
@rob729 already done.

**Comment by rob729** [comment]
Ok.
The issue was open so i thought it was pending.
