### ISSUE TITLE
Share Button for sharing app

### ISSUE THREAD

**Issue by tanmayrauth** [fossasia/neurolab-android#532]
**Describe the bug**
A share button that will help the app details among friends.

**Expected Behavior**
Ideally when this button is clicked app sharing options across various social media should pop up and app details can be share through it.

**Would you like to work on the issue?**
Yes I would like to work on this issue and will implement the share feature for this app.

**Comment by dheerajkotwani** [comment]
@jddeep can I work on this?

**Comment by tanmayrauth** [comment]
I am already working on this and also raised PR for the same

**Comment by dheerajkotwani** [comment]
okay @tanmayrauth
