### ISSUE TITLE
Show meaningful message when no dataset present in the device

### ISSUE THREAD

**Issue by dipu989** [fossasia/neurolab-android#533]
**Actual Behaviour.**  
Nothing appears on the share data activity when the device has no datasets present.

**Expected Behaviour**  
There should be a message in Share data activity when there are no datasets
in the device.

**Steps to reproduce it**  
If there are no datasets present, click on the share button from the navigation drawer.

**Would you like to work on the issue?**
Yes

**Comment by dheerajkotwani** [comment]
Can I work on this issue?

**Comment by dipu989** [comment]
@dheerajkotwani  I have already resolved this one! Please find other unassigned issue or feel free to open one, if you encounter any. :)

**Comment by dheerajkotwani** [comment]
okay @dipu989
