### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by rob729** [fossasia/neurolab-android#536]
**Describe the issue**

The link present for CONTRIBUTING.md in Readme.md is broken.

**Would you like to work on the issue?**

yes

**Comment by chintustacks** [comment]
Yes i would like to work on this issue please assign to me,

**Comment by chintustacks** [comment]
completed this issue please check and review this

**Comment by rob729** [comment]
@chintu-stacks I already mentioned in the issue description that I am working on this issue.
Next time remember to first claim the issue and confirm whether anyone else is working on the issue or not.

**Comment by chintustacks** [comment]
sure ,

**Comment by adityastic** [comment]
> Please avoid making things like Contributing.md. We already have FOSSASIA Best Practices. You should not explain how to make a PR. There are tons of resources online. This should not be covered here. Please help to focus on code to bring this project forward. Thank you. Will delete contributing.md therefore.

**Comment by adityastic** [comment]
I won't allow this, sorry
