### ISSUE TITLE
Align Settings Fragment options

### ISSUE THREAD

**Issue by neel1998** [fossasia/neurolab-android#55]
**Actual Behaviour**

Samples per seconds, Bins, Number Channels are not aligned properly

**Expected Behaviour**

Aligned them to left

**Steps to reproduce it**

Open Settings from menu

**Screenshots of the issue**

![screenshot_20190218-144618](https://user-images.githubusercontent.com/32041242/52940374-6a196d00-338c-11e9-83d8-36c5dd372c00.png)

**Would you like to work on the issue?**

yes

**Comment by Dev-Aslan** [comment]
yes

**Comment by prateekj117** [comment]
@iamareebjamal May I work on this issue?

**Comment by iamareebjamal** [comment]
This is Android issue
