### ISSUE TITLE
Last item visited from menu bar always remains selected

### ISSUE THREAD

**Issue by manan025** [fossasia/neurolab-android#551]
**Describe the bug**
When I click on a item in menu bar, say Memory graph, then when I click on device's back button, the item in menu bar remains selected.

**Expected Behavior**
The device should forget the selected item and in the menu bar, none of the items should remain selected.

**Steps to reproduce it**
Open the side bar, open Focus/ Relax/ Memory graph and then click on the device's back button. Reopen the side menu, you will see the item you visited was selected.

**Screenshots of the issue**
![Screenshot_2019-12-17-10-04-36-40_243bed73eac0221c54c37b9ad745f08a](https://user-images.githubusercontent.com/40761012/70965147-b1f44800-20b4-11ea-857b-81703d7b0aac.png)

**System Information**
<table>
<tr>
  <td>Device</td><td>Realme 1</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Pie 9.0</td>
</tr>
</table>

**Would you like to work on the issue?**
No

**Comment by rob729** [comment]
@jddeep Can I work on this issue?

**Comment by adityastic** [comment]
@rob729 go ahead
