### ISSUE TITLE
There was an error while parsing the package. Error while installing the apk.

### ISSUE THREAD

**Issue by manan025** [fossasia/neurolab-android#552]
**Describe the bug**
While installing the package, error occurs -> **There was an error while parsing the package.**

**Expected Behavior**
The apk should be installed.

**Steps to reproduce it**
Install the apk on Android 5.x

**Logcat for the issue**
Not Applicable

**Screenshots of the issue**
![Screenshot_2019-12-17-10-43-00](https://user-images.githubusercontent.com/40761012/70966694-16fe6c80-20ba-11ea-947f-c2c8f694db40.png)

**System Information**
<table>
<tr>
  <td>Device</td><td>Lenovo Tab3 7 Essential</td><td>Yureka AO5510</td>
</tr>
<tr>
  <td>Android version/OS</td><td>5.0 (Android Lollipop)</td><td>5.1 (Android Lollipop)</td>
</tr>
</table>

**Would you like to work on the issue?**
No

**Comment by jddeep** [comment]
@dipu989 @kshitiz-kumar Can you please check this?

**Comment by kshitiz-kumar** [comment]
@jddeep This may be because the app's min-sdk version is 23 and for android 5.1 it is 22.

**Comment by asaikarthikeya** [comment]
Is this still active ?  i would like to work on this.

**Comment by CloudyPadmal** [comment]
min-sdk version is 23
