### ISSUE TITLE
Values are Not aligned vertically with title in Feedback settings Fragment 

### ISSUE THREAD

**Issue by neel1998** [fossasia/neurolab-android#56]
**Actual Behaviour**

Values are not aligned with title.

**Expected Behaviour**

Align values vertically to the title. 

**Steps to reproduce it**

Open Feedback settings menu

**Screenshots of the issue**

![screenshot_20190218-150656](https://user-images.githubusercontent.com/32041242/52941618-4277d400-338f-11e9-8f39-c5cb21511e6a.png)

**Would you like to work on the issue?**

Yes

**Comment by itsSiddharthGupta** [comment]
Can i work upon this issue?? @CloudyPadmal @mariobehling

**Comment by neel1998** [comment]
@itsSiddharthGupta  I have already filed a PR solving this isuue long back

**Comment by itsSiddharthGupta** [comment]
But you have not reviewed or updated it to make it pass all the tests...

**Comment by itsSiddharthGupta** [comment]
> 
> 
> @itsSiddharthGupta I have already filed a PR solving this isuue long back

Ok i won't be working upon this issue

**Comment by Dev-Aslan** [comment]
can i work on this issue?
