### ISSUE TITLE
Adding a ripple effect to all the card view

### ISSUE THREAD

**Issue by kshitiz-kumar** [fossasia/neurolab-android#571]
**Actual Behaviour.**  
In the application whenever the user clicks on any of the card view (Focus,Relax etc) it simply directs to other screen. There should be ripple effect generated whenever the user clicks on any of the card view, so as to improve the user experience.

**Expected Behaviour**  
A ripple effect on clicking the card views

**Steps to reproduce it**  
Check the focus , relax , memory graph and meditate card view.

**Would you like to work on the issue?**
Yes

**Comment by kshitiz-kumar** [comment]
@adityastic @jddeep

**Comment by adityastic** [comment]
Sure
