### ISSUE TITLE
Replace Checkbox with Switch

### ISSUE THREAD

**Issue by refactor-droidyy** [fossasia/neurolab-android#574]
**Actual Behaviour.**  
Currently, in setting there are checkboxes for performing single on/off operation.

**Expected Behaviour**  
The Checkbox should be replaced by Switches.

**Steps to reproduce it**  
Open Settings

**Additional context**  
Checkboxes allow the user to select multiple options from a set. Instead, it will be good to use a switch.

**Would you like to work on the issue?**
Yes

**Comment by refactor-droidyy** [comment]
@adityastic can I work on this?

**Comment by adityastic** [comment]
Sure
