### ISSUE TITLE
App Crashes when Adding non - numerical values to settings field

### ISSUE THREAD

**Issue by neel1998** [fossasia/neurolab-android#58]
**Actual Behaviour**

When adding non - numerical value in the settings fields, and the opening the feedback settings app crashes.

**Expected Behaviour**

Disallow entering non numeric values in settings field.

**Steps to reproduce it**

Add some alphabets in any settings field and then open feedback fragment

**Would you like to work on the issue?**

Yes

**Comment by jddeep** [comment]
This issue has already been seen into and there is a PR open for this.

**Comment by jddeep** [comment]
Kindly remove this issue.
