### ISSUE TITLE
Making the list of audio files inside meditation's cards clickable.

### ISSUE THREAD

**Issue by AkshobhyaP** [fossasia/neurolab-android#589]
**Actual Behaviour.**
To go to the audio screen from the list you need to press the tiny play buttons at the corner.

**Expected Behaviour**  
Make the whole list view clickable, so that it is easier to open any sound option.

**Steps to reproduce it**  
Open any card inside meditate screen ->  select any audio option

**Additional context**  
![Screenshot_20200120-093235](https://user-images.githubusercontent.com/18425237/72698067-7abbff80-3b68-11ea-9389-70ac1ab95abb.jpg)

**Would you like to work on the issue?**
Yes.

**Comment by ho-dor** [comment]
Same as #588
