### ISSUE TITLE
Scrolling in Meditation Activity should be on whole activity instead just the list.

### ISSUE THREAD

**Issue by dheerajkotwani** [fossasia/neurolab-android#590]
**Describe the bug**
Scrolling in Meditation Activity

**Expected Behavior**
Whole page should scroll instead of just the list.

**Steps to reproduce it**
Open the meditation activity
Switch to landscape mode or take any mobile with small display size.
Try scrolling the list.

**Screenshots of the issue**
![neurolabs](https://user-images.githubusercontent.com/44086235/72714501-cbe1e880-3b94-11ea-9e70-ce65d3e7cc40.gif)

**System Information**
<table>
<tr>
  <td>Device</td><td>Redmi Note 4</td>
</tr>
<tr>
  <td>Android version/OS</td><td>Naugat 7.0</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes

**Comment by ho-dor** [comment]
I think the current implementation with fixed brain icon the correct way to do it. What do you think @jddeep @adityastic
