### ISSUE TITLE
fix: Unnamed Logged Data Save

### ISSUE THREAD

**Issue by 991rajat** [fossasia/neurolab-android#600]
**Describe the bug**
When editing the name of the logged data if we left it empty it is also being saved.

**Expected Behavior**
Generate an error message in the edit text when saving an unnamed file.

**Steps to reproduce it**
Logged Data > Edit Any File > Clear The Name > Save it.

**System Information**
<table>
<tr>
  <td>Device</td><td>e.g. Moto E2</td>
</tr>
<tr>
  <td>Android version/OS</td><td>eg: Nougat 7.1.2</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes

**Comment by dipu989** [comment]
@adityastic @jddeep Would like to work on this issue!

**Comment by 991rajat** [comment]
I would like to work on this issue please. @dipu989

**Comment by dipu989** [comment]
I only asked because you  were already working on different issue! @991rajat

**Comment by 991rajat** [comment]
Are you a mentor? Is this issue is approved for working? @dipu989 
https://github.com/fossasia/neurolab-android/issues/600#issuecomment-577978469 
about this are you referring to others to work on this issue or you would like to do it ?

**Comment by dipu989** [comment]
No, I am a contributor. I was interested in solving this issue. 
Contributors here are advised to solve one issue at a time by mentors, so I asked so that I could proceed!

**Comment by 991rajat** [comment]
I have opened 2 issues and if both get approved you can work on any of them. @dipu989

**Comment by 991rajat** [comment]
@dipu989 Go Ahead You can work on this. Get Approval from mentors on this one.
