### ISSUE TITLE
ReadMe file not descriptive enough

### ISSUE THREAD

**Issue by itsSiddharthGupta** [fossasia/neurolab-android#63]
**Actual Behaviour**
ReadMe file is not that descriptive about the app. No functioning of the app is described clearly.

**Expected Behaviour**
It should briefly explain the working as well as purpose of the app. Also it should tell the contribution process.This will definitely help those beginner contributors.

**Steps to reproduce it**
1.) By explaining even a little about the working of app, features (developed or to be developed).
2.) By attaching screen shots of the working app.

**Would you like to work on the issue?**
I personally think that creator should update the readme for the better understanding of an

**Comment by jddeep** [comment]
The Readme here is directed to describe the neurolab project at this stage. The full working app functionality is currently in development so screenshots will be updated eventually.

**Comment by dilum1995** [comment]
@itsSiddharthGupta and @jddeep 
Also, we can add a link to our gitter chat room in the readme as other projects have.

**Comment by lilliCao** [comment]
I checked the current UI. It's a little unclear and repeated in many places. I would suggest putting all the settings, about us in the navigation bar on the left and remove the programs mode from the nav and center them on the first page.  I have a quite form view of how it better look like.
