### ISSUE TITLE
Update app UI flow related mockups to develop app layout screens

### ISSUE THREAD

**Issue by dilumdesilva** [fossasia/neurolab-android#64]
**Actual Behaviour**

Since the neurolab application is currently in the development phase, it would be great to have UI mockups in the README.md to contribute for people who looking to contribute to this project.

Currently, the project is missing application flow related UI mockups

**Expected Behaviour**
It would be much helpful for all the contributors of the project, if maintainers of neurolab could add some rough UI mockups which explain the UI need to be developed with the application flow.

That way contributors can engage with app development even at the early stage.

**Steps to reproduce it**

1. By attaching UI mockups related to the application flow in the readme file

**Would you like to work on the issue?**
Yes, 

If maintainers/admins of the project can provide some rough UI flow related mockups, I would like to go ahead and update the readme and start working on the application layouts.

**Comment by itsSiddharthGupta** [comment]
I've opened a similar issue!!!  👍

**Comment by jddeep** [comment]
@dilum1995 There is a similar issue open #63 . Please check the open issues before opening a new one, Cheers ! :)

**Comment by dilumdesilva** [comment]
Hello @itsSiddharthGupta and @jddeep 

I am sorry, I actually didn't notice that I thought it's something related to just updating the readme with app related development details.

Thanks for the notice anyways.

**Comment by CloudyPadmal** [comment]
Addressed in #63
