### ISSUE TITLE
Having two issue templates to maintain the project 

### ISSUE THREAD

**Issue by dilumdesilva** [fossasia/neurolab-android#65]
**Actual Behaviour**
The project only has one issue template to 

- report a bug 
- suggest a feature

this it's hard to identify or group issues depending on it's purpose or the content 

**Expected Behaviour**
Since the project is in the development stage it would be great to have two issue templates to maintain issues related to bug reporting or feature requests.

So, when a particular contributor wants to create a issue, once he/she press on the new issue but it will ask/popup the contributor to select the issue type (either bug reporting or feature suggest). Depending on the issue type they can create issues.

below attached is a screenshot of expected issue types

<img width="1120" alt="screen shot 2019-03-02 at 2 16 50 am" src="https://user-images.githubusercontent.com/23298579/53665423-67265280-3c91-11e9-964c-00d3accd4519.png">

**Steps to reproduce it**

1. By creating two issue template types to report bugs or suggest features from project settings.

**Would you like to work on the issue?**
Since only the maintainers/contributors of the project has access to create new issue templates, I think one of them have to add it to the project

**Comment by 0x7FFF** [comment]
I can work on this issue and submitted a pull request
