### ISSUE TITLE
No description or sumamry in f-droid

### ISSUE THREAD

**Issue by Bubu** [fossasia/neurolab-android#655]
**Describe the issue**

See here: https://f-droid.org/packages/io.neurolab/

This is probably because your fastlane file have no .txt extensions, see here for how this needs to look like: https://staging.f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure

**Comment by jddeep** [comment]
Go ahead with the fix! Thanks.

**Comment by asaikarthikeya** [comment]
I would like to work on this issue.

**Comment by asaikarthikeya** [comment]
I would like to work on this issue . Could  you guide how to get started.
@jddeep 
Thankyou.

**Comment by Bubu** [comment]
@asaikarthikeya The page linked in the first post has been improved a lot since: https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ You'll find all necessary information there

**Comment by asaikarthikeya** [comment]
I edited full_description ,short_description  and title in fastlane file with  full_description,txt ,short_description.txt  and title.txt .

Is this what need to be done in order to obtain the description in f-droid.

**Comment by asaikarthikeya** [comment]
I added .txt extension to full_description ,short_description and title in fastlane file.

Is this the way to obtain the description in f-droid ?

**Comment by asaikarthikeya** [comment]
I added .txt extension to full_description ,short_description and title in fastlane file.

Is this the way to obtain the description in f-droid ?

**Comment by Bubu** [comment]
On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya <notifications@github.com> wrote:
>I added .txt extension to full_description ,short_description and title in fastlane file.
>
>Is this the way to obtain the description in f-droid ?
>
>

There needs to be a new version of the application with these changes included this to work.

**Comment by asaikarthikeya** [comment]
> On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya ***@***.***> wrote: I added .txt extension to full_description ,short_description and title in fastlane file. Is this the way to obtain the description in f-droid ?
> There needs to be a new version of the application with these changes included this to work.

#666  Does this solve the issue or anything more needs to be done?

**Comment by asaikarthikeya** [comment]
> On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya ***@***.***> wrote: I added .txt extension to full_description ,short_description and title in fastlane file. Is this the way to obtain the description in f-droid ?
> There needs to be a new version of the application with these changes included this to work.

#666 Does this solve the issue?

**Comment by asaikarthikeya** [comment]
> On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya ***@***.***> wrote: I added .txt extension to full_description ,short_description and title in fastlane file. Is this the way to obtain the description in f-droid ?
> There needs to be a new version of the application with these changes included this to work.
#666 
@Bubu Any Updates?Did this solve the issue?

**Comment by Bubu** [comment]
On October 18, 2020 7:57:03 AM GMT+02:00, asaikarthikeya <notifications@github.com> wrote:
>> On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya ***@***.***> wrote: I added .txt extension to full_description ,short_description and title in fastlane file. Is this the way to obtain the description in f-droid ?
>> There needs to be a new version of the application with these changes included this to work.
>#666 
>@Bubu Any Updates?Did this solve the issue?
>

I don't know. If you followed the docs it should be solved when there is a new release published for fdroid.

**Comment by asaikarthikeya** [comment]
> On October 18, 2020 7:57:03 AM GMT+02:00, asaikarthikeya ***@***.***> wrote: > On October 14, 2020 6:34:04 PM GMT+02:00, asaikarthikeya ***@***.***> wrote: I added .txt extension to full_description ,short_description and title in fastlane file. Is this the way to obtain the description in f-droid ? > There needs to be a new version of the application with these changes included this to work. #666 @Bubu Any Updates?Did this solve the issue?
> I don't know. If you followed the docs it should be solved when there is a new release published for fdroid.

Will my PR be accepted now? I am participating in hacktoberfest, i would like this to counted.

**Comment by aadityasinha-dotcom** [comment]
Hi @Bubu,
I am highly interested in contributing but I am new to all of this.
Can you please tell me where to start? I'll be highly obliged.

**Comment by asaikarthikeya** [comment]
@aadityasinha-dotcom Hi aditya , its good to see you showing interest contributing in this project .There is a PR open for this issue,kindly look for other issue's with no PR's linked :) 
All the best.
