### ISSUE TITLE
on clicking on import it takes back to home screen

### ISSUE THREAD

**Issue by Aditya185** [fossasia/neurolab-android#70]
**Actual Behaviour**

on clicking on import it takes back to home screen

**Expected Behaviour**

it should takes to some storage location

**Would you like to work on the issue?**

i would like to work on this issue,if any one explains what exactly it suppose to do.

**Comment by CloudyPadmal** [comment]
Closing this issue as the feature is not yet implemented. Import is to add a saved data set into the app.
