### ISSUE TITLE
In settings menu,summary should be shown,and updated value should also be shown 

### ISSUE THREAD

**Issue by Aditya185** [fossasia/neurolab-android#73]
**Actual Behaviour**
the summary are not showing 

Please state here what is currently happening.

**Expected Behaviour**
it show the summary of the editTextPreference
State here what the feature should enable the user to do.
if the user update the summary,the updated value should be shown.

**Screenshots of the issue**
![screenshot_20190304-192013](https://user-images.githubusercontent.com/31539068/53737782-7684e600-3eb3-11e9-87c5-ec1e2b15ebd0.jpeg)
--After changes
![screenshot_20190304-192853](https://user-images.githubusercontent.com/31539068/53738005-07f45800-3eb4-11e9-8532-e8ce08fb4366.jpeg)
--After updating a value
![screenshot_20190304-192905](https://user-images.githubusercontent.com/31539068/53738050-22c6cc80-3eb4-11e9-80e0-d3b10a1ea10d.jpeg)

**Would you like to work on the issue?**
I would like to work on this issue
Let us know if this issue should be assigned to you or tell us who you think could help to solve this issue.

**Comment by Dev-Aslan** [comment]
Can i work on this issue? And please tell me what to do when i resolve this issue
