### ISSUE TITLE
keyboard enter key/tick key should work as "ok" button when changing values in settings preferences

### ISSUE THREAD

**Issue by neel1998** [fossasia/neurolab-android#76]
**Actual Behaviour**

Currently keyboard enter key doesn't do anything

**Expected Behaviour**

keyboard enter key/tick key should work as "ok" button when changing values in settings preferences
**Steps to reproduce it**

Try to change settings preferences and press enter

**Would you like to work on the issue?**

yes

**Comment by apoorv-katiyar** [comment]
hey @CloudyPadmal Can i work on this issue?
