### ISSUE TITLE
Add OnDestroy( ) callback in MainActivity to avoid memory leaks.

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#86]
**Actual Behaviour**
Currently the MainActivity lacks the onDestroy( ) callback. The callback is essential for providing a way to the Android System for carrying out the necessary shutdown operations and for releasing of the resources to prevent memory leakages. For instance, currently there are a couple of view listeners (NavigtationItemSelectedListener for navigation view and DrawerListener for the drawer layout) which have not been set to null/removed. Though they are view references but they pose a risk of short-term memory leaks in unexpected situations. Its a good android development practice to utilize the framework callbacks correctly for their purposes. In my opinion, the onDestroy( ) callback won't only serve the purpose of writing robust and optimized code but also enforce the same invariant in the future for other developers.

**Expected Behaviour**
onDestroy( ) callback should be overridden and listeners should be set to null/removed in the callback to prevent short-term memory leaks. 

**Would you like to work on the issue?**
 I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal @mariobehling Can I work on this issue.

**Comment by iamareebjamal** [comment]
Memory leaks can't happen if the listeners are set on the widgets contained in the parent itself. They can only happen if the listener is contained in a component whose life cycle exceeds that of the activity
