### ISSUE TITLE
Make NeuroSettings class Encapsulated.

### ISSUE THREAD

**Issue by suresh-gandhi** [fossasia/neurolab-android#88]
**Actual Behaviour**
Currently, the NeuroSettings class lacks encapsulation as 
- The instance variables (samplesPerSecond, bins, numChannels) are declared as public instead of private. I believe external classes do not need to know about the data/information directly but they shall still be able to get/set the data. This is because by making the variables public we are allowing the external classes to be able to depend on it and therefore losing the flexibility to change the implementation at a later point without affecting users of the class.
- Setters are missing.

**Expected Behaviour**
- The instance variables (samplesPerSecond, bins, numChannels) should be declared as private.
- Inorder for other classes to interact with the variables the class(NeuroSettings) should have properly implemented getter and setter methods.

**Would you like to work on the issue?**
I would like to work on this issue.

**Comment by suresh-gandhi** [comment]
@CloudyPadmal @mariobehling @iamareebjamal Can I work on this issue.

**Comment by Dev-Aslan** [comment]
I would like to work on this issue

**Comment by suresh-gandhi** [comment]
@Dev-Aslan It's great that you are quite enthusiastic to contribute. I have resolved this issue and referenced the PR as you can see. You can work upon other open(unassigned issues) or perhaps could even raise your own issues. Thanks.

**Comment by Dev-Aslan** [comment]
@suresh-gandhi thanks for reply

**Comment by RohitJain1103** [comment]
@suresh-gandhi I have made a similar issue and PR for defaultFFTData class. Please have a look.

**Comment by suresh-gandhi** [comment]
Sure @RohitJain1103. It's great that you did it already as I was going to do it.
