### ISSUE TITLE
Minor improvements to UI in  Menu

### ISSUE THREAD

**Issue by abhiramready** [fossasia/neurolab-android#93]
**Actual Behaviour**

No detail UI in nav_header_main.xml

**Expected Behaviour**

Add a logo and improve UI experience
**Steps to reproduce it**

Add Logo and change Background

**Screenshots of the issue**

![Screenshot (23)](https://user-images.githubusercontent.com/40287643/54842027-c3135280-4cf6-11e9-89c6-e86d2327d9f6.png)

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment]
Nav header is now updated
